// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A Point is an X, Y coordinate pair. The axes increase right and down.
 */
export interface Point {
    "X": number;
    "Y": number;
}

/**
 * A Rectangle contains the points with Min.X <= X < Max.X, Min.Y <= Y < Max.Y.
 * It is well-formed if Min.X <= Max.X and likewise for Y. Points are always
 * well-formed. A rectangle's methods always return well-formed outputs for
 * well-formed inputs.
 * 
 * A Rectangle is also an [Image] whose bounds are the rectangle itself. At
 * returns color.Opaque for points in the rectangle and color.Transparent
 * otherwise.
 */
export interface Rectangle {
    "Min": Point;
    "Max": Point;
}
