// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineColorOption は選べる折れ線の色 1 つ（画面の色見本）。
 */
export interface EngineColorOption {
    /**
     * Value は `#rrggbb`（設定ファイルにもこの形で入る）。
     */
    "value": string;

    /**
     * Label は色の名前（画面に出す）。
     */
    "label": string;
}
