// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AnalyzeService は確定した局面をエンジンに解析させる Service（Phase 4）。
 * 
 * **エンジンは USI を話す相手**（`analyze` → `core/usi/client`）。同梱の `engine` でも
 * 外部エンジンの exe でも `prokishi.exe` でも、ここは変わらない
 * （`_docs/phase4-engine-usi.md`）。
 * 
 * ⚠️ **エンジンのプロセスは 1 回の解析のあいだだけ生きる。** 解析を始めるときに
 * 起こし、終わったら `quit` する。「ずっと解析していたい」は**時間無制限の解析**
 * （考える秒数を「無制限」にする）として表すので、そのあいだは生きている。
 * 
 * **局面はここが持たない。** 解析するのは常に「今 PositionService が持っている局面」で、
 * フロントから SFEN を受け取らない（フロントに局面の写しを持たせない、という
 * PositionService の方針と揃える。渡してもらう形にすると、訂正した直後に古い局面を
 * 解析する経路ができる）。
 * 
 * **同時に走るのは 1 本だけ。** 新しく始めると前の解析は打ち切る。検討ツリー
 * （Phase 5）で複数の枝を並べて解析したくなったらここを増やすが、**そのときも
 * 「今どの枝を見ているか」は UI 側の話**で、解析そのものは 1 局面ずつ独立している
 * （設計原則1）。
 * 
 * 途中経過はイベントで流す。反復深化は深さが 1 つ終わるたびに答えが更新されるので、
 * 終わるまで黙っていると数秒間固まったように見える。
 * 
 * 	analyze:info    深さが 1 つ完走した（Progress）
 * 	analyze:done    解析が終わった（Result）
 * 	analyze:failed  始められなかった・エラーになった（理由の文字列）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckEngine は設定したエンジンに実際に繋いでみる（設定タブの「接続を確認」）。
 * 
 * **確かめたら閉じる。** 解析していないのにプロセスを残さない。
 * 起動にかかった時間も返すので、**解析のたびに払うコストがここで分かる。**
 */
export function CheckEngine(): $CancellablePromise<$models.EngineCheck> {
    return $Call.ByID(232459897);
}

/**
 * Start は今の局面の解析を始める。**ここでエンジンを起こす。**
 * 
 * seconds は考える秒数。**0 以下なら「止めるまで考え続ける」**（＝そのあいだ
 * エンジンも生きている）。時間で打ち切っても、それまでに完走した深さの評価値は出る
 * （設計原則3）。
 * 
 * ⚠️ **局面が確定していなければエラー。** 手番か駒台の先後が未決だと SFEN が
 * 組み上がらない（決めていないことを勝手に決めない。設計原則5）。訂正 UI で
 * 決めてもらう以外に手は無いので、ここは警告ではなくエラーにする。
 */
export function Start(seconds: number): $CancellablePromise<$models.AnalyzeState> {
    return $Call.ByID(3590958719, seconds);
}

/**
 * State は今の状態を返す（何も始めない）。フロントの初期表示用。
 */
export function State(): $CancellablePromise<$models.AnalyzeState> {
    return $Call.ByID(3910027670);
}

/**
 * Stop は走っている解析を打ち切る。**打ち切っても評価値は出る**ので、
 * 「やめる」というより「ここまでで良い」に近い。
 */
export function Stop(): $CancellablePromise<$models.AnalyzeState> {
    return $Call.ByID(3300023813);
}
