// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureService は Wails にバインドする、GUI からのキャプチャ操作。
 * ロジックは持たず、ikkyoku ルートパッケージ(Capture / SavePNG / DefaultOutDir)を
 * 呼ぶだけに徹する(ikkyoku/CLAUDE.md: 将棋のロジックを書かない、状態を持たない)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture はガイド枠の内側を撮って PNG 保存し、保存先パスとサムネイルを返す。
 * フロントの「撮る」ボタンとグローバルホットキーの両方から呼ばれる。
 * 1 回のキャプチャは他のキャプチャと完全に独立している(状態を持たない)。
 */
export function Capture(): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(3605231503);
}

/**
 * HideFrame は枠を隠す。フロント(ツールバーの✕)と Alt+F4 の両方から呼ばれる。
 * 
 * 閉じずに隠すだけなのは、枠が「見せるための UI」ではなく「撮る領域の定義」だから。
 * 隠しても HWND は生きているので、そのまま Alt+S で同じ領域を撮り続けられる。
 * むしろ隠したほうが、ツールバーやガイド枠が写り込む余地が原理的に無くなる。
 * 
 * 枠を隠した結果として可視ウィンドウが 1 枚も無くなると、アプリが動いているのに
 * 操作できない状態になる。それを避けるため、メイン画面がまだ出ていなければ出す。
 */
export function HideFrame(): $CancellablePromise<void> {
    return $Call.ByID(2583042588);
}

/**
 * Layout は枠ウィンドウが描くべき寸法を返す。フロントは起動時にこれを呼び、
 * CSS 変数に反映してからガイド枠を描く(定数の二重管理を避けるため)。
 */
export function Layout(): $CancellablePromise<$models.GuideLayout> {
    return $Call.ByID(3905037405);
}

/**
 * ShowFrame は隠した枠を出し直す。メイン画面のボタンから呼ばれる。
 */
export function ShowFrame(): $CancellablePromise<void> {
    return $Call.ByID(3510559659);
}
