// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureService は Wails にバインドする、GUI からのキャプチャ操作。
 * ロジックは持たず、ikkyoku ルートパッケージ(Capture / SavePNG / DefaultOutDir)を
 * 呼ぶだけに徹する(ikkyoku/CLAUDE.md: 将棋のロジックを書かない、状態を持たない)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as guide$0 from "../github.com/ShinteLab/ikkyoku/guide/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture はガイド枠の内側を撮って PNG 保存し、保存先パスとサムネイルを返す。
 * フロントの「撮る」ボタンとグローバルホットキーの両方から呼ばれる。
 * 1 回のキャプチャは他のキャプチャと完全に独立している(状態を持たない)。
 * 
 * ⚠️ **枠が出ていなければ撮らない**(2026-08-10 決定)。技術的には隠れていても
 * HWND は生きているので撮れてしまうが、**「今どこを撮るのか」が画面に出ていない
 * まま撮れるのは事故のもと**。枠は「どこを撮るか」の定義そのものなので、
 * **見えていることを撮れる条件にする。**
 */
export function Capture(): $CancellablePromise<$models.CaptureResult> {
    return $Call.ByID(3605231503);
}

/**
 * CopyImage は保存済みの PNG をクリップボードへ入れる。デバッグタブから呼ばれる。
 * 
 * **撮った画像をメモリに抱えず、保存したファイルを読み直す。** 1 回のキャプチャは
 * 他のキャプチャと独立という方針(ikkyoku/CLAUDE.md)に沿って「直近の画像」を
 * 持たずに済むし、後から一覧を作ってどの 1 枚でもコピーできるようにするときも
 * そのまま使える。読み直しの費用は数 MB の PNG のデコード 1 回だけ。
 * 
 * パスの持ち主はフロント(直前の CaptureResult.Path)。テキストのコピーは Wails
 * ランタイムの Clipboard.SetText で完結するのでフロント側にあり、画像だけがここに来る
 * (画像はランタイムに口が無く、Win32 を直接叩く必要があるため。clipboard_windows.go)。
 */
export function CopyImage(path: string): $CancellablePromise<void> {
    return $Call.ByID(1696139771, path);
}

/**
 * FitFrame は**画面に出ている盤**を探して、そこへガイド枠を合わせる。
 * 
 * **枠を盤に合わせること自体が認識の精度に効く。** suteme は「盤だけが写っている画像」
 * なら素直に解けるので、枠が盤に合っているほど当たりが良くなる。位置合わせを楽にする
 * だけの機能ではない。
 * 
 * 探すのは**枠の内側 → 枠がいるディスプレイ全体**の順(findBoard)。「枠の内側だけ」を
 * やめたのは、枠を先に盤へ近づけておく必要があり、**それができるなら手で合わせるのと
 * あまり変わらない**ため。今は「その画面に今出ている盤に合わせる」という機能になっている。
 * 
 * 画面全体を撮るときは**自分のウィンドウを画面から消してから撮る**:
 * 
 *   - 枠は Hide() して撮り、撮り終えたら戻す。赤いガイド枠が写ると格子の検出を汚す
 *   - メイン画面は消さず、撮った画像の上でその矩形を塗り潰す(maskWindows)。
 *     **メイン画面には `<shogi-board>` が本物の盤を描いている**ので、放っておくと
 *     中継の盤より綺麗なそちらが選ばれる
 * 
 * 隠して撮り直すぶん、押してから結果が出るまでに一呼吸ある(枠が一瞬消える)。
 * **撮る操作(Capture)にこの方式を持ち込まないこと。** あちらはタイミングに依存しない
 * 決定論的な領域算出が要点で、こちらはユーザーが押した 1 回きりの操作なので待てる。
 * 
 * 枠の位置はユーザーが手で合わせたものなので、**怪しい検出結果では動かさない**。
 * 判断は recognize.DetectRegion の信頼度・最小サイズ・「枠の中で半分に縮む候補は採らない」
 * の 3 つ。
 */
export function FitFrame(): $CancellablePromise<$models.FitResult> {
    return $Call.ByID(2955080287);
}

/**
 * FrameVisible は枠が今出ているか。**タイトルバーのトグルの初期状態**に使う
 * (起動した時点で出ていることがある —— 設定「起動時に盤面を探す」)。
 */
export function FrameVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(3608586286);
}

/**
 * HideFrame は枠を隠す。**入口は 3 つ**（枠のツールバーの ✕ / Alt+F4 /
 * **メイン画面のタイトルバーのトグル**）。⚠️ どれを通っても `frame:visible` で
 * 知らせるので、**トグルの表示が食い違わない**。
 * 
 * 閉じずに隠すだけなのは、枠が「見せるための UI」ではなく「撮る領域の定義」だから。
 * 隠しても HWND は生きているので、**出し直せば前と同じ領域に戻る**（位置を覚えている）。
 * 
 * ⚠️ **隠しているあいだは撮れない**（`Capture` の `requireFrame`）。技術的には
 * 撮れてしまうが、**「今どこを撮るのか」が画面に出ていないまま撮れるのは事故のもと**
 * なので、見えていることを条件にしてある。
 * 
 * 枠を隠した結果として可視ウィンドウが 1 枚も無くなると、アプリが動いているのに
 * 操作できない状態になる。それを避けるため、メイン画面がまだ出ていなければ出す
 * (起動時に出しているので普通は既に出ているが、**保険は外さないこと**)。
 */
export function HideFrame(): $CancellablePromise<void> {
    return $Call.ByID(2583042588);
}

/**
 * Layout は枠ウィンドウが描くべき寸法を返す。フロントは起動時にこれを呼び、
 * CSS 変数に反映してからガイド枠を描く(定数の二重管理を避けるため)。
 */
export function Layout(): $CancellablePromise<guide$0.Layout> {
    return $Call.ByID(3905037405);
}

/**
 * Quit はアプリを終了する。**フロントの自前の✕はどちらもここへ来る**
 * (枠のツールバーのメニュー ▼ → 終了 / メイン画面のタイトルバーの ✕)。
 * 
 * ⚠️ **メイン画面も Frameless にしたので、あちらの✕も `WindowClosing` を通らない**
 * (自前のボタンなので OS の WM_CLOSE が飛ばない。wails3 skill pitfalls.md)。
 * 終了時にやることを 2 か所に書かないよう、**入口はこの 1 本に寄せる**。
 * 
 * **枠の✕は「隠す」であって「終了」ではない**(HideFrame。領域の定義を生かすため)。
 * そのため枠しか出ていない状態では終了する手段が無く、メイン画面を一度出してから
 * 閉じるしかなかった。枠だけで使っているときの終了の入口がこれ。
 * 
 * メイン画面を閉じたときと同じものを残す必要があるので、**Quit の前に位置・サイズを
 * 保存する**(app.Quit() が WindowClosing のフックを通す保証は無い)。二重に保存されても
 * 同じ記録から書くので害は無い。
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3340511680);
}

/**
 * Recognizer は直近の読み込み結果を返す。**読み込み直さない。**
 * フロントが起動時に状態を表示するためだけに 3.5MB を読み直すのを避ける。
 */
export function Recognizer(): $CancellablePromise<$models.RecognizerStatus> {
    return $Call.ByID(1357821961);
}

/**
 * ReloadRecognizer は駒種推論器を読み込み直し、その結果を返す。起動時にも呼ぶ。
 * 
 * **再読み込みの入口を用意しているのは、学習データを育てながら使うため。**
 * suteme は一度読み込んだ推論器をキャッシュするので、学習データを更新しても
 * これを呼ぶまで(あるいは再起動するまで)反映されない。
 * 訂正 → 学習データ更新 → 撮り直す、というループを回すのにアプリの再起動を
 * 挟みたくない。
 */
export function ReloadRecognizer(): $CancellablePromise<$models.RecognizerStatus> {
    return $Call.ByID(3817107600);
}

/**
 * RepairMain はメイン画面を隠して出し直す。枠のメニューの「メイン画面を描き直す」から呼ばれる。
 * 
 * **メイン画面が真っ黒になって何も触れなくなったときの復帰手段。**
 * Wails は Hide()/Show() でそれぞれ WebView2 の `PutIsVisible(false)`/`(true)` を呼ぶので、
 * 最小化の復帰で不可視のまま取り残されたコントローラを表示状態に戻せる
 * (現象と経緯は diagservice.go)。
 * 
 * **入口を枠のメニューに置いたのが要点。** 黒くなるのはメイン画面なので、
 * メイン画面の中にボタンを置いても押せない。枠は別ウィンドウなので生きている。
 * 
 * これで絵が戻るなら「見えなくされていた」、戻らないならレンダラ側が死んでいる、
 * という切り分けにもなる(心拍のログと合わせて読むこと)。
 */
export function RepairMain(): $CancellablePromise<void> {
    return $Call.ByID(705668711);
}

/**
 * ShowFrame は隠した枠を出し直す。メイン画面のタイトルバーのボタンから呼ばれる。
 */
export function ShowFrame(): $CancellablePromise<void> {
    return $Call.ByID(3510559659);
}

/**
 * ShowMain はメイン画面を出して前面に持ってくる。枠のメニューから呼ばれる。
 * 
 * **枠からメイン画面を出す手段が「撮る」か「枠を✕で隠す」しか無かった。** どちらも
 * 副作用が目的とずれている(撮りたくないのに撮る / 位置合わせに使う枠が消える)ので、
 * メイン画面を見たいときの入口をメニューに作った。
 * 
 * tab は開いてほしいタブ("board" / "debug" / "settings")。空なら今のタブのまま。
 * **イベントは Show の前に出す**(Capture と同じ理由。前面に来た時点で目的のタブが
 * 開いている状態にする)。メイン画面は隠れていてもフロントは動いているので、
 * 非表示のあいだに出したイベントも受け取れる。
 */
export function ShowMain(tab: string): $CancellablePromise<void> {
    return $Call.ByID(909839475, tab);
}
