// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagService は「画面が真っ黒になって何も触れなくなる」現象を切り分けるための計測。
 * 
 * 2026-08-08 に実機で 1 回起きた。そのとき手元に残っていたのは
 * `[WebView2] Focus failed: The group or resource is not in the correct state`
 * が 4 行だけで、**Go 側は無傷だった**(黒くなったあとのホットキーで PNG が保存できている)。
 * 
 * 疑っているのは Wails beta.3 の最小化まわり。`WM_SIZE / SIZE_MINIMIZED` で
 * Wails は `chromium.Hide()`(= WebView2 の `PutIsVisible(false)`)を呼び、
 * **元に戻すのは復帰時の 1 か所だけ**(`webview_window_windows.go` の
 * SIZE_RESTORED / SIZE_MAXIMIZED 分岐。しかも条件付き)。ここを取りこぼすと
 * コントローラは不可視のまま戻らず、次の状態になる:
 * 
 *   - 真っ黒(不可視なので何も合成されない)
 *   - 入力を受け付けない(不可視のコントローラは入力を取らない)
 *   - `MoveFocus` が「状態が正しくない」で失敗する(= 観測されたログ)
 *   - **フロントの JS は動き続けている**
 * 
 * 最後の 1 点が決め手になる。**心拍が続いたまま画面が黒いなら「見えなくされている」、
 * 心拍が止まるならレンダラが死んでいる。** この 2 つは手当てが正反対
 * (前者は表示し直せば戻る = CaptureService.RepairMain、後者は読み込み直すしかない)
 * なので、次に起きた 1 回で判別が付くようにしておく。
 * 
 * **2026-08-13 に 2 回目が起き、この計測が答えを出した。**
 * **main と frame の心拍が同じ秒に止まり**(両方 hidden=false・heap は 11/12MB)、
 * 以後 `Eval failed` が通らなくなった。**最小化説はウィンドウ単位の話なので 2 枚同時は
 * 説明できず、`Eval` が通らない = ページではなく WebView2 の側が居ない**
 * (ページさえ生きていれば ExecuteScript は通る)。2 枚は同じ WebView2 環境に
 * ぶら下がっているので、ブラウザプロセスが落ちればまとめて黒くなる。
 * **= 下の「心拍が止まる」側で、RepairMain は効かない**(戻す相手が居ない)。
 * 詳細と次の一手は CLAUDE.md の同名の節。
 * 
 * **状態は持つが、局面やキャプチャには一切関与しない。** 計測だけの Service。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Heartbeat はフロントから定期的に呼ばれる。window は "frame" / "main"。
 * hidden は document.hidden(隠れている窓はタイマーを間引かれる。上の閾値を参照)。
 * 
 * **戻り値を持たない。** フロントは結果を見ないし、返す意味のあるものも無い。
 */
export function Heartbeat(window: string, heapMB: number, hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(176398178, window, heapMB, hidden);
}

/**
 * ReportError はフロントで拾えなかった例外を Go 側のログに流す。
 * 
 * **今までフロントの例外はどこにも出ていなかった**(webview の DevTools を
 * 開いていない限り消える)。黒くなった件では何も出ていないが、
 * 「出ていない」ことを根拠にするには、まず出る経路が要る。
 */
export function ReportError(window: string, kind: string, message: string, stack: string): $CancellablePromise<void> {
    return $Call.ByID(1502194890, window, kind, message, stack);
}
