// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FontService は「駒の字」（設定タブ）。
 * 
 * **端末に入っているフォントから駒の字を焼いて、webview に流す。**
 * 同梱できるフォントがライセンスの都合で限られる一方、**自分の端末に入っている
 * フォントを自分の端末で表示に使うのは再配布ではない**、というのがこの機能の
 * 拠り所（`piecefont` のパッケージコメント）。
 * 
 * ⚠️ **焼いたフォントをファイルに書き出す口を持たないこと。** 書き出せると
 * 「その端末で表示する」を越えてしまう（元フォントの条項が効く側の話になる）。
 * 
 * ⚠️ **盤に当てるのはフロント。** ここが返すのは family 名と data URL までで、
 * どの要素に当てるかは CSS の `--shogi-font` の仕事。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add は端末のフォントを 1 つ登録して、**そのまま使う状態にする。**
 * 
 * ⚠️ **登録しただけで使わない、という状態を作らない。** 登録する操作は
 * 「この字で見たい」なので、そのあともう一度選ばせるのは 1 手多い
 * （気が変わったら一覧から選び直せばよい）。
 */
export function Add(path: string, index: number): $CancellablePromise<$models.FontState> {
    return $Call.ByID(1788907595, path, index);
}

/**
 * Preview は**登録せずに**焼いて data URL を返す（選ぶ前に字を見るため）。
 * 
 * ⚠️ **family を毎回変えている。** 同じ名前で焼き直すと、webview 側で
 * どちらが当たるかがブラウザ任せになり、**プレビューが前のフォントのまま**に
 * 見えることがある。登録の family（`PieceFontFamily`）とも必ず違う名前にすること。
 */
export function Preview(path: string, index: number): $CancellablePromise<$models.FontFace> {
    return $Call.ByID(4220716188, path, index);
}

/**
 * Remove は登録を消す。
 * 
 * ⚠️ **使っていたものを消したら同梱に戻すこと。** 戻さないと
 * **一覧に無いものを選んでいる状態**になる。
 */
export function Remove(id: string): $CancellablePromise<$models.FontState> {
    return $Call.ByID(1577628096, id);
}

/**
 * Rename は表示名を付け替える（**空にすると元フォントの名前に戻る**）。
 */
export function Rename(id: string, name: string): $CancellablePromise<$models.FontState> {
    return $Call.ByID(502531866, id, name);
}

/**
 * Scan は端末に入っているフォントを探す。
 * 
 * ⚠️ **押したときだけ呼ぶこと。** 実測で 190 ファイル・577MB を読んで 1 秒弱かかる
 * （起動のたびに走らせる類の処理ではない）。フロントは待ちを出す。
 */
export function Scan(): $CancellablePromise<$models.FontScan> {
    return $Call.ByID(2863649889);
}

/**
 * SetGyoku は王を玉で書くかを変える（`""` / `"black"` / `"white"` / `"both"`）。
 * 
 * ⚠️ **知らない値は「王のまま」に倒す**（`NormalizeGyoku`）。断らないのは、
 * **どう倒したかが画面にそのまま出る**から（返した `FontState` を描くだけで、
 * 選び直されたことが見える）。
 */
export function SetGyoku(v: string): $CancellablePromise<$models.FontState> {
    return $Call.ByID(953537289, v);
}

/**
 * SetHidariUma は馬を左馬で書くかを変える。⚠️ **先後の区別は無い**（盤全体）。
 */
export function SetHidariUma(on: boolean): $CancellablePromise<$models.FontState> {
    return $Call.ByID(3267147414, on);
}

/**
 * State は今の設定を返す（設定タブを開いたとき・起動時）。
 */
export function State(): $CancellablePromise<$models.FontState> {
    return $Call.ByID(2089914269);
}

/**
 * Use は使うフォントを切り替える（**空文字なら同梱に戻す**）。
 */
export function Use(id: string): $CancellablePromise<$models.FontState> {
    return $Call.ByID(1308109803, id);
}
