// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as legal$0 from "../github.com/ShinteLab/ikkyoku/legal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as position$0 from "../github.com/ShinteLab/ikkyoku/position/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recognize$0 from "../github.com/ShinteLab/ikkyoku/recognize/models.js";

/**
 * AddLine は候補手を枝として足した結果（解析タブの候補手の右クリック）。
 */
export interface AddLine {
    /**
     * State は足したあとの解析タブの状態。**今見ている局面は動いていない。**
     */
    "state": StudyState;

    /**
     * FirstID は最初に生えた節点（**0 なら 1 手も増えていない**＝全部が既にあった）。
     * 
     * ⚠️ **0 を失敗として扱わないこと。** 候補が本譜と同じ手順なら 1 手も
     * 増えないのが正しい（そのときは既にある手順を辿るだけ）。
     */
    "firstId": number;

    /**
     * Added は新しく生えた手数。
     */
    "added": number;

    /**
     * Note は全部は足せなかった理由（足せたなら空）。**エラーではない**（設計原則3）。
     */
    "note": string;
}

/**
 * AnalyzeEngine は解析に参加しているエンジン 1 つ（フロントの表示の単位）。
 */
export interface AnalyzeEngine {
    /**
     * ID は設定の登録 ID。**イベントの振り分けはこれ。**
     */
    "id": string;

    /**
     * Label は設定タブで付けた名前（未設定ならファイル名 / 「同梱エンジン」）。
     * 
     * **繋ぐ前から出せる名前。** エンジンが `id name` で名乗る名前は繋いで初めて
     * 分かるので、起動を待っているあいだの見出しにはこちらが要る。
     */
    "label": string;

    /**
     * Name はエンジンが名乗った名前（`id name`。まだ繋いでいなければ空）。
     */
    "name": string;

    /**
     * Builtin は同梱のエンジンか。
     */
    "builtin": boolean;
}

/**
 * AnalyzeState は今解析中かどうか。フロントの初期表示と、開始・停止の応答に使う。
 */
export interface AnalyzeState {
    "running": boolean;
    "seq": number;

    /**
     * SFEN は解析にかけた局面（開始時のみ入る）。何を評価した値なのかを示す。
     */
    "sfen": string;

    /**
     * Engines は解析に参加しているエンジン（登録順）。
     * 
     * **何が出した評価値なのかは見せること。** 繋ぎ先を差し替えられる以上、
     * 評価値だけ出して出所を伏せると比べようがない。**複数走るなら尚更**で、
     * フロントはこの並びのぶんだけ結果の枠を作る（起動を待つあいだも見出しが出る）。
     */
    "engines": AnalyzeEngine[] | null;
}

/**
 * AppSettings はメイン画面の設定タブに出す設定。
 * 
 * **ikkyoku.Config そのものを返していない。** あちらは CLI 用の項目(領域・ディスプレイ番号)
 * まで含む「設定ファイルの形」で、画面に出すものとは範囲が違う。ここは
 * 「設定タブが読み書きするもの」だけを持つ。
 */
export interface AppSettings {
    /**
     * FitOnStartup は起動時に盤面を探してガイド枠を合わせるか。
     */
    "fitOnStartup": boolean;

    /**
     * Training は訂正した局面を suteme へ登録する設定。
     */
    "training": TrainingSettings;

    /**
     * Engines は登録した USI エンジンの一覧（登録順）。
     * 
     * ⚠️ **1 つに絞らない**（2026-08-11）。「解析に使う」を付けたものが
     * **同時に走って結果が並ぶ**ので、ここは常に一覧で扱う。
     */
    "engines": EngineSettings[] | null;

    /**
     * PonanzaConstant は評価値 → 勝率の変換に使う定数（解析タブの勝率バー）。
     * 
     * **既定値（1500）は解決済みで返る**（`analyze.PonanzaConstantOr`）。
     * ⚠️ **フロントに既定値を書かないこと** —— training の Host/Port と同じで、
     * 2 か所に持つと既定を変えたときに食い違う。
     */
    "ponanzaConstant": number;

    /**
     * Path は設定ファイルの場所。**表示のためだけ。** 手で編集したくなったときに
     * 探さずに済むよう出しておく(学習データの置き場所もこのファイルにある)。
     */
    "path": string;
}

/**
 * CaptureResult はフロントに返すキャプチャ結果。
 * 
 * 盤面の認識結果も含むが、**認識できなくてもキャプチャは成功**として返す
 * (設計原則3「段階的に劣化すること」。撮った 1 局面が残ることのほうが大事で、
 * 認識はその上に乗るもの)。認識だけが失敗したときは SFEN が空になり、
 * RecognizeError に理由が入る。
 */
export interface CaptureResult {
    "path": string;
    "width": number;
    "height": number;

    /**
     * data:image/png;base64,... のサムネイル(等倍)
     */
    "thumbnail": string;

    /**
     * 盤面部分のみ。認識できなければ空
     */
    "sfen": string;

    /**
     * 盤面検出の信頼度(0.0〜1.0)
     */
    "confidence": number;

    /**
     * 局面として成立していない点
     */
    "warnings": string[] | null;

    /**
     * 駒台の推定枚数(先後不明)
     */
    "handTotal": { [_ in string]?: number } | null;

    /**
     * RecognizeError は「撮れたが認識できなかった」ときの理由。
     * キャプチャ自体の失敗はこれではなく Capture のエラーで表す。
     */
    "recognizeError": string;

    /**
     * Debug は認識の観測情報(盤面と判定した矩形・マス割り・使った推論器)。
     * **デバッグタブ専用。** 撮った画像にこの矩形を重ねることで、認識が外れたときに
     * 「座標がずれているのか、駒種を外しているのか」を切り分けられる。
     * 
     * 画像を Go 側で描いて返さないのは、サムネイルが既に等倍 PNG の base64 で、
     * 描き込んだ 2 枚目を積むとイベントのペイロードが倍になるため。矩形の座標だけを
     * 渡してフロントで重ねれば軽く、マスごとの確信度をホバーで出すこともできる。
     */
    "debug"?: recognize$0.Debug | null;
}

/**
 * EditCell は 1 マスの見え方。フロントが盤に重ねる当たり判定と、
 * ドラッグ中のゴースト表示に使う。
 */
export interface EditCell {
    /**
     * Mark は SFEN のマス表記（"P" / "+p" / 空マスは ""）。
     */
    "mark": string;

    /**
     * Name は日本語（"先手の歩" / "空"）。ホバーと読み上げ用。
     */
    "name": string;

    /**
     * Empty は空マスか。Mark == "" と同じだが、フロントで判定を間違えないよう明示する。
     */
    "empty": boolean;
}

/**
 * EditState は訂正の状態一式。**操作のたびにこれを丸ごと返す。**
 */
export interface EditState {
    /**
     * Loaded は局面を読み込んでいるか（まだ何も撮っていなければ false）。
     */
    "loaded": boolean;

    /**
     * BoardSFEN は盤面部分の SFEN。手番が未決でも取れる。
     */
    "boardSfen": string;

    /**
     * SFEN は局面全体の SFEN。**手番が未決なら空**（決めていない手番を勝手に
     * 先手へ倒さないため。position.Position.SFEN と同じ理由）。
     */
    "sfen": string;

    /**
     * LabelSFEN は**画像のラベルとしての** SFEN。**局面が確定していなくても必ず入る。**
     * 
     * ⚠️ **表示にも解析にも使わないこと。** 用途は suteme への学習データ登録だけで、
     * 手番が未決でも `b` と書き、決まっているぶんの持ち駒を必ず載せる
     * （`position.Position.LabelSFEN` の注記を読むこと）。**画面に出すのは SFEN**。
     */
    "labelSfen": string;

    /**
     * LabelNotes は LabelSFEN を組み立てるために妥協した点（手番を先手にした・
     * 先後未決の持ち駒を落とした）。**送る前にユーザーへ出す**（黙って捨てない）。
     */
    "labelNotes": string[] | null;

    /**
     * Turn は 0=不明 / 1=先手番 / 2=後手番。
     */
    "turn": number;
    "turnLabel": string;

    /**
     * MoveNumber は手数。0 は不明。
     */
    "moveNumber": number;

    /**
     * Cells は 81 マス（SFEN 記述順。rank*9+file）。
     */
    "cells": EditCell[] | null;

    /**
     * Inventory は「存在するはずの駒」の在庫。**訂正 UI の駒箱はこれを並べる。**
     */
    "inventory": position$0.Stock[] | null;

    /**
     * Warnings は局面として成立していない点。**エラーではない**（直している最中は
     * 壊れていて当たり前）。
     */
    "warnings": string[] | null;

    /**
     * Dirty は認識結果から変更したか。「訂正を捨てて戻す」を出すかの判断に使う。
     */
    "dirty": boolean;
}

/**
 * EngineCheck は「接続を確認」の結果。
 * 
 * **エラーも値として返す**（error にしない）。設定タブに出す情報であって、
 * 呼び出しが失敗したわけではない。エンジンを置く前に確かめるのは普通の使い方。
 */
export interface EngineCheck {
    /**
     * ID は確かめた登録の ID。**どの行の結果なのかを示す**（設定タブには
     * エンジンが並んでいるので、結果を返す先が分からないと出せない）。
     */
    "id": string;

    /**
     * Label は設定タブで付けた名前。
     */
    "label": string;

    /**
     * Path は確かめた実行ファイル（同梱なら空）。
     */
    "path": string;

    /**
     * Builtin は同梱のエンジンか。
     */
    "builtin": boolean;

    /**
     * OK は繋がったか。
     */
    "ok": boolean;

    /**
     * Name は繋がったエンジンの名前（`id name`）。
     */
    "name": string;

    /**
     * Options はエンジンが宣言した option の数。
     */
    "options": number;

    /**
     * Applied は `isready` の前に送った `setoption` の数（**既定値を含む**）。
     * 
     * **送ったことが見えないと、効いているか確かめようがない**（option には
     * 応答が返らない）。宣言より少ないのが普通（button と空の既定値は送らない）。
     */
    "applied": number;

    /**
     * StartupMS は起動から `readyok` までの所要ミリ秒。
     * 
     * **解析タブで最初に解析するときに 1 回だけ待つ**（そのあとは接続を使い回す）。
     * 繋ぎ先を選ぶ材料として出す。
     */
    "startupMs": number;

    /**
     * Error は繋がらなかった理由（日本語）。
     */
    "error": string;
}

/**
 * EngineSettings は登録した USI エンジン 1 つ（設定タブの 1 行）。
 * 
 * **「外部エンジンを使うか」の真偽値は持たない。** パスが空なら同梱のエンジン、
 * 入っていれば外部エンジン。2 つ持つと「パスが入っているのに無効」という
 * 食い違いが起きる（ikkyoku.EngineEntry の注記と同じ）。
 */
export interface EngineSettings {
    /**
     * ID は一覧の中でこのエンジンを指す識別子（操作のときに渡す）。
     */
    "id": string;

    /**
     * Name は画面に出す名前。**空欄なら Go 側が解決した既定の名前が入る**
     * （パスのファイル名 / 「同梱エンジン」）。フロントで組み立てないこと。
     */
    "name": string;

    /**
     * Custom は名前を人が付けたか（false なら Name は既定の解決結果）。
     * 
     * 入力欄に既定の名前を書き込んでしまうと、パスを変えても名前が追従しなく
     * なるので、フロントは Custom のときだけ Name を欄に入れる。
     */
    "custom": boolean;

    /**
     * Path は USI エンジンの実行ファイル。空なら同梱。
     */
    "path": string;

    /**
     * Builtin は同梱のエンジンを使う状態か（Path が空）。**表示用。**
     * フロントで `path === ""` を判定させないため（判断の基準を Go 側に置く）。
     */
    "builtin": boolean;

    /**
     * OptionCount は config.json に書いた setoption の数。**表示用。**
     * 
     * option は画面に出していない（エンジンごとに違いすぎる）ので、
     * **書いたものが効いていることだけ**は見えるようにしておく。
     */
    "optionCount": number;

    /**
     * Enabled は解析に使うか。**外した登録も残る。**
     */
    "enabled": boolean;
}

/**
 * EvalGraph はグラフを描くのに要るもの一式。
 * 
 * **横軸の範囲を決める材料もここに入れる。** フロントが `StudyState` と
 * 突き合わせて計算すると、2 つの値が別のタイミングで届くぶんだけずれる。
 */
export interface EvalGraph {
    /**
     * Series はエンジンごとの折れ線（**解析に登場した順**）。
     */
    "series": EvalSeries[] | null;

    /**
     * Ply は今見ている手（**縦線を引く位置**）。
     */
    "ply": number;

    /**
     * Number は今見ている局面の棋譜手数。
     */
    "number": number;

    /**
     * Last は手順の最後の棋譜手数（**横軸の「自動」の右端**）。
     */
    "last": number;

    /**
     * First は根の棋譜手数（横軸の左端。根が初期局面なら 0）。
     */
    "first": number;

    /**
     * IDs は今の経路の節点 id（**ply 番目の要素がその手数の節点**。IDs[0] は根の 0）。
     * 
     * ⚠️ **グラフを押したときの行き先はこれで引く。** 枝が入ってからは
     * 「手数 → 局面」が一意に決まらないので、**手数から `GoTo` の引数を作らないこと。**
     */
    "ids": number[] | null;
}

/**
 * EvalPoint は折れ線の 1 点＝「ある局面に、あるエンジンが付けた評価値」。
 */
export interface EvalPoint {
    /**
     * ID は手順ツリーの節点（**押したときに `GoTo` へ渡す値**。0 は根）。
     * 
     * ⚠️ **記録の鍵はこれ**（2026-08-13。以前は手数だった）。枝が入ると同じ手数の
     * 局面が何個もあるので、**手数では「どの局面に付いた評価値か」を指せない。**
     */
    "id": number;

    /**
     * Ply は根からの手数（0 なら根の局面）。**横軸の位置を出すのに使う。**
     */
    "ply": number;

    /**
     * Number は棋譜の数え方の手数（**グラフの横軸**）。
     * 
     * ⚠️ **Ply と別に持つ。** 根は初期局面とは限らない（撮った中盤の局面が
     * 根になる）ので、根の手数ぶんずれる。横軸に出すのは棋譜の手数のほう。
     */
    "number": number;

    /**
     * CP はセンチポーン相当（**先手が良ければ正**）。Mate が 0 のときだけ意味を持つ。
     * 
     * ⚠️ **符号は `analyze` が先手視点に直したもの。** ここでも表示側でも
     * いじらないこと（手番が入れ替わっても折れ線の上下の意味が変わらないのは、
     * これが揃っているから）。
     */
    "cp": number;

    /**
     * Mate は詰みまでの手数（0 なら詰みなし。正なら先手が詰ます）。
     */
    "mate": number;

    /**
     * Label は表示用の文字列（"+230" / "▲詰 5手"）。
     * 
     * **書式は `analyze` が組み立てたものをそのまま持つ。** フロントで作り直さない。
     */
    "label": string;

    /**
     * Depth はその評価値が出たときの深さ（ツールチップ用）。
     */
    "depth": number;

    /**
     * Move はその局面に至った手の表記（根なら空）。ツールチップに出す。
     */
    "move": string;
}

/**
 * EvalSeries はエンジン 1 つぶんの折れ線。
 */
export interface EvalSeries {
    /**
     * EngineID は設定の登録 ID。**同じ exe を option 違いで登録できる**ので、
     * 折れ線を分ける鍵はパスでも名前でもなくこれ。
     */
    "engineId": string;

    /**
     * Label は設定タブで付けた名前（凡例に出す）。
     */
    "label": string;

    /**
     * Points は Ply の昇順。
     */
    "points": EvalPoint[] | null;
}

/**
 * FitResult はガイド枠の自動フィットの結果。
 * 
 * **見つからなかったことはエラーではない。** 盤が映っていない画面に枠を置いている
 * ことも、認識が外すこともある(設計原則3)。そのときは Fitted=false と理由を返し、
 * 枠は 1px も動かさない。error になるのはキャプチャ自体ができなかったときだけ。
 */
export interface FitResult {
    "fitted": boolean;
    "confidence": number;
    "message": string;
}

/**
 * GuideLayout は枠ウィンドウの描画寸法(CSS px)をフロントに渡すための型。
 */
export interface GuideLayout {
    "borderPx": number;
    "toolbarPx": number;
}

/**
 * KifuLoad は棋譜を読み込んだ結果（入力タブの「棋譜を貼り付ける」）。
 */
export interface KifuLoad {
    /**
     * State は読み込んだあとの解析タブの状態。**そのまま showStudy に渡す。**
     */
    "state": StudyState;

    /**
     * Summary は「何手読み込んだか」の 1 行（対局者・棋戦が分かれば添える）。
     */
    "summary": string;

    /**
     * Note は全部は載らなかった理由（載ったなら空）。
     * 
     * ⚠️ **これはエラーではない。** 途中で止まっても、そこまでの手順は正しいので
     * 解析できる（設計原則3）。**フロントで空でないことをエラー扱いしないこと。**
     */
    "note": string;
}

/**
 * RecognizerStatus は駒種推論器(suteme)の読み込み状況。
 */
export interface RecognizerStatus {
    /**
     * Source は読み込み元。設定で指定していなければ空(suteme 既定の探索に任せる)。
     */
    "source": string;
    "ready": boolean;
    "error": string;
}

/**
 * StudyState は解析タブが描くのに要るもの一式。
 * 
 * **EditState とは別の型にしてある。** 見た目が似ていても中身の意味が違う
 * （あちらは「直している最中の局面」、こちらは「確定した局面」）ので、
 * 片方の型をもう片方に流用しない。訂正の道具（在庫の負の値・足りない駒）は
 * ここには要らない。
 */
export interface StudyState {
    /**
     * Loaded はまだ何も採っていなければ false。
     */
    "loaded": boolean;

    /**
     * BoardSFEN は盤面部分の SFEN。盤を描くのに使う。
     */
    "boardSfen": string;

    /**
     * SFEN は局面全体の SFEN。**確定しているので必ず埋まる**
     * （Adopt が確定していない局面を断るため）。
     */
    "sfen": string;

    /**
     * Turn は 1=先手番 / 2=後手番（0 は Loaded == false のときだけ）。
     */
    "turn": number;
    "turnLabel": string;

    /**
     * MoveNumber は SFEN の数え方の手数（0 は不明）。
     */
    "moveNumber": number;

    /**
     * Hands は駒台。**訂正タブと違い未決は残っていない**（確定した局面なので）。
     */
    "hands": position$0.Stock[] | null;

    /**
     * Warnings は局面として成立していない点。**確定を止めはしない**
     * （詰将棋のような「論理的におかしくても正しい」局面があるため。設計原則3）。
     * 解析タブでも出しておくのは、変な評価値が出たときの手掛かりになるから。
     */
    "warnings": string[] | null;

    /**
     * Black / White は対局者名（**棋譜を読んだときだけ埋まる。無ければ空**）。
     * 
     * 勝率バーの左右に出す。⚠️ **空のときに「先手」「後手」で埋めないこと** ——
     * 名前が分かっているのか、既定を出しているだけなのかが区別できなくなる。
     * **既定の文言は表示側が持つ。**
     */
    "black": string;
    "white": string;

    /**
     * SourceURL は棋譜の取得元（**URL から読んだときだけ埋まる**。2026-08-13）。
     * 
     * **空でなければ「再読み込み」を出す**（`ReloadKifu`）。⚠️ **フロントで
     * URL 欄の中身から判断しないこと** —— 入力タブの欄はいつでも書き換えられるので、
     * **今の手順がどこから来たか**とは別物になる。
     */
    "sourceUrl": string;

    /**
     * RootSFEN は根の局面（採ったときの局面）。**エンジンに渡すのはこれ + Played。**
     */
    "rootSfen": string;

    /**
     * First は根までに指された手数（＝**棋譜の手数の起点**）。
     * 
     * ⚠️ **`Move.Number` は根からの手数で、棋譜の手数ではない**（あちらは `GoTo` に
     * 渡す値も兼ねているので、起点をずらせない）。撮った 41 手目の局面を根にすると
     * `Move.Number` は 1 から始まるので、**画面に手数として出すときは First を足す**。
     * 評価値グラフの横軸（`EvalGraph.First`）と**同じ値**にすること。
     */
    "first": number;

    /**
     * Nodes は手順ツリーの全部の手（**表示順**。日本語表記つき）。
     * 
     * ⚠️ **一直線ではない**（2026-08-13）。`Depth` が字下げ、`Main` が本譜側。
     * 並びは「その手 → 枝 → 本譜の続き」で、**ある手の子孫は必ずその直後に固まる**。
     */
    "nodes": position$0.Node[] | null;

    /**
     * CurrentID は今見ている節点（0 なら根）。**手順リストの現在位置。**
     */
    "currentId": number;

    /**
     * Line は今の経路の節点 id（**ply 番目がその手数の節点**。先頭は根の 0）。
     * 
     * ⚠️ **連続解析が次に進む先はここから取る。** 枝に居るならその枝を辿る。
     */
    "line": number[] | null;

    /**
     * Ply は今どこまで進めて見ているか（0 なら根）。
     * 
     * **len(Line)-1 より小さいことがある**（戻って見ている状態）。
     */
    "ply": number;

    /**
     * Played は今の局面までの手（USI）。**解析に渡す moves そのもの。**
     */
    "played": string[] | null;

    /**
     * Legal は今の局面で指せる手。**駒をクリックしたときに光らせる先。**
     * 
     * ⚠️ **同じ移動先に成りと不成の 2 つが並ぶことがある。** どちらを指すかは
     * 人が決めることなので、**Go 側で片方に丸めないこと**（UI が聞く）。
     */
    "legal": legal$0.Move[] | null;

    /**
     * LegalError は合法手を出せなかった理由（出せたなら空）。
     * 
     * ⚠️ **これはエラーにしない**（設計原則3）。玉の欠けた局面などでは手を進められ
     * ないが、盤は描けるし解析タブに居ることもできる。**手が指せなくなるだけ。**
     */
    "legalError": string;
}

/**
 * TrainingSendResult は登録の結果。
 */
export interface TrainingSendResult {
    "id": string;

    /**
     * Duplicate は同じ画像が既に登録されていたか。**失敗ではない**
     * （suteme は画像のハッシュで再送を弾き、既存の ID を返す）。
     */
    "duplicate": boolean;
    "entries": number;
}

/**
 * TrainingSettings は「訂正盤面を suteme に登録する」の設定。
 * 
 * **ikkyoku.TrainingConfig をそのまま返していない。** 画面に出すのは
 * 「実際に送る先(Target)」まで組み立てた形で、Host/Port の既定値の解決を
 * フロントに持たせないため(既定は training パッケージが持つ)。
 */
export interface TrainingSettings {
    "enabled": boolean;
    "host": string;
    "port": number;
    "token": string;

    /**
     * Target は上の設定から組み立てた接続先("http://host:port")。**表示用。**
     */
    "target": string;
}

/**
 * TrainingStatus は「今このサーバに送ってよいか」の問い合わせ結果。
 * 
 * **エラーも値として返す**（error にしない）。設定タブに出す情報であって、
 * 呼び出しが失敗したわけではない。相手が起動していないのは普通の状態。
 */
export interface TrainingStatus {
    /**
     * Configured は「訂正盤面を suteme に登録する」が有効か。
     */
    "configured": boolean;

    /**
     * Target は問い合わせ先("http://host:port")。
     */
    "target": string;

    /**
     * Reachable は応答があったか。
     */
    "reachable": boolean;

    /**
     * Error は応答が無い・受け付けられない場合の理由（日本語）。
     */
    "error": string;

    /**
     * Accepting は suteme 側で登録受付が有効になっているか。
     * 
     * ⚠️ **false でも、同じマシン（ループバック）からは送れる。** suteme は
     * ループバックを認証・受付判定の手前で素通しにしている。**送信の可否として
     * 使わないこと**（送れるのに送れないと表示することになる）。表示に留める。
     */
    "accepting": boolean;

    /**
     * Detailed 以下は、相手が素性を明かした場合だけ入る（ループバックか、
     * 正しいトークンを持っている場合）。
     */
    "detailed": boolean;
    "entries": number;
    "capacity": number;
    "dataVersion": string;

    /**
     * Note は「そのまま送れるとは限らない」ことを伝える補足（空なら無し）。
     */
    "note": string;
}
