// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recognize$0 from "../github.com/ShinteLab/ikkyoku/recognize/models.js";

/**
 * CaptureResult はフロントに返すキャプチャ結果。
 * 
 * 盤面の認識結果も含むが、**認識できなくてもキャプチャは成功**として返す
 * (設計原則3「段階的に劣化すること」。撮った 1 局面が残ることのほうが大事で、
 * 認識はその上に乗るもの)。認識だけが失敗したときは SFEN が空になり、
 * RecognizeError に理由が入る。
 */
export interface CaptureResult {
    "path": string;
    "width": number;
    "height": number;

    /**
     * data:image/png;base64,... のサムネイル(等倍)
     */
    "thumbnail": string;

    /**
     * 盤面部分のみ。認識できなければ空
     */
    "sfen": string;

    /**
     * 盤面検出の信頼度(0.0〜1.0)
     */
    "confidence": number;

    /**
     * 局面として成立していない点
     */
    "warnings": string[] | null;

    /**
     * 駒台の推定枚数(先後不明)
     */
    "handTotal": { [_ in string]?: number } | null;

    /**
     * RecognizeError は「撮れたが認識できなかった」ときの理由。
     * キャプチャ自体の失敗はこれではなく Capture のエラーで表す。
     */
    "recognizeError": string;

    /**
     * Debug は認識の観測情報(盤面と判定した矩形・マス割り・使った推論器)。
     * **デバッグタブ専用。** 撮った画像にこの矩形を重ねることで、認識が外れたときに
     * 「座標がずれているのか、駒種を外しているのか」を切り分けられる。
     * 
     * 画像を Go 側で描いて返さないのは、サムネイルが既に等倍 PNG の base64 で、
     * 描き込んだ 2 枚目を積むとイベントのペイロードが倍になるため。矩形の座標だけを
     * 渡してフロントで重ねれば軽く、マスごとの確信度をホバーで出すこともできる。
     */
    "debug"?: recognize$0.Debug | null;
}

/**
 * FitResult はガイド枠の自動フィットの結果。
 * 
 * **見つからなかったことはエラーではない。** 盤が映っていない画面に枠を置いている
 * ことも、認識が外すこともある(設計原則3)。そのときは Fitted=false と理由を返し、
 * 枠は 1px も動かさない。error になるのはキャプチャ自体ができなかったときだけ。
 */
export interface FitResult {
    "fitted": boolean;
    "confidence": number;
    "message": string;
}

/**
 * GuideLayout は枠ウィンドウの描画寸法(CSS px)をフロントに渡すための型。
 */
export interface GuideLayout {
    "borderPx": number;
    "toolbarPx": number;
}

/**
 * RecognizerStatus は駒種推論器(suteme)の読み込み状況。
 */
export interface RecognizerStatus {
    /**
     * Source は読み込み元。設定で指定していなければ空(suteme 既定の探索に任せる)。
     */
    "source": string;
    "ready": boolean;
    "error": string;
}
