// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as position$0 from "../github.com/ShinteLab/ikkyoku/position/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recognize$0 from "../github.com/ShinteLab/ikkyoku/recognize/models.js";

/**
 * AnalyzeState は今解析中かどうか。フロントの初期表示と、開始・停止の応答に使う。
 */
export interface AnalyzeState {
    "running": boolean;
    "seq": number;

    /**
     * SFEN は解析にかけた局面（開始時のみ入る）。何を評価した値なのかを示す。
     */
    "sfen": string;

    /**
     * Engine は繋がっているエンジンの名前（未接続なら空）。
     * 
     * **何が出した評価値なのかは見せること。** 繋ぎ先を差し替えられる以上、
     * 評価値だけ出して出所を伏せると比べようがない。
     */
    "engine": string;
}

/**
 * AppSettings はメイン画面の設定タブに出す設定。
 * 
 * **ikkyoku.Config そのものを返していない。** あちらは CLI 用の項目(領域・ディスプレイ番号)
 * まで含む「設定ファイルの形」で、画面に出すものとは範囲が違う。ここは
 * 「設定タブが読み書きするもの」だけを持つ。
 */
export interface AppSettings {
    /**
     * FitOnStartup は起動時に盤面を探してガイド枠を合わせるか。
     */
    "fitOnStartup": boolean;

    /**
     * Training は訂正した局面を suteme へ登録する設定。
     */
    "training": TrainingSettings;

    /**
     * Engine は解析に使う USI エンジン。
     */
    "engine": EngineSettings;

    /**
     * Path は設定ファイルの場所。**表示のためだけ。** 手で編集したくなったときに
     * 探さずに済むよう出しておく(学習データの置き場所もこのファイルにある)。
     */
    "path": string;
}

/**
 * CaptureResult はフロントに返すキャプチャ結果。
 * 
 * 盤面の認識結果も含むが、**認識できなくてもキャプチャは成功**として返す
 * (設計原則3「段階的に劣化すること」。撮った 1 局面が残ることのほうが大事で、
 * 認識はその上に乗るもの)。認識だけが失敗したときは SFEN が空になり、
 * RecognizeError に理由が入る。
 */
export interface CaptureResult {
    "path": string;
    "width": number;
    "height": number;

    /**
     * data:image/png;base64,... のサムネイル(等倍)
     */
    "thumbnail": string;

    /**
     * 盤面部分のみ。認識できなければ空
     */
    "sfen": string;

    /**
     * 盤面検出の信頼度(0.0〜1.0)
     */
    "confidence": number;

    /**
     * 局面として成立していない点
     */
    "warnings": string[] | null;

    /**
     * 駒台の推定枚数(先後不明)
     */
    "handTotal": { [_ in string]?: number } | null;

    /**
     * RecognizeError は「撮れたが認識できなかった」ときの理由。
     * キャプチャ自体の失敗はこれではなく Capture のエラーで表す。
     */
    "recognizeError": string;

    /**
     * Debug は認識の観測情報(盤面と判定した矩形・マス割り・使った推論器)。
     * **デバッグタブ専用。** 撮った画像にこの矩形を重ねることで、認識が外れたときに
     * 「座標がずれているのか、駒種を外しているのか」を切り分けられる。
     * 
     * 画像を Go 側で描いて返さないのは、サムネイルが既に等倍 PNG の base64 で、
     * 描き込んだ 2 枚目を積むとイベントのペイロードが倍になるため。矩形の座標だけを
     * 渡してフロントで重ねれば軽く、マスごとの確信度をホバーで出すこともできる。
     */
    "debug"?: recognize$0.Debug | null;
}

/**
 * EditCell は 1 マスの見え方。フロントが盤に重ねる当たり判定と、
 * ドラッグ中のゴースト表示に使う。
 */
export interface EditCell {
    /**
     * Mark は SFEN のマス表記（"P" / "+p" / 空マスは ""）。
     */
    "mark": string;

    /**
     * Name は日本語（"先手の歩" / "空"）。ホバーと読み上げ用。
     */
    "name": string;

    /**
     * Empty は空マスか。Mark == "" と同じだが、フロントで判定を間違えないよう明示する。
     */
    "empty": boolean;
}

/**
 * EditState は訂正の状態一式。**操作のたびにこれを丸ごと返す。**
 */
export interface EditState {
    /**
     * Loaded は局面を読み込んでいるか（まだ何も撮っていなければ false）。
     */
    "loaded": boolean;

    /**
     * BoardSFEN は盤面部分の SFEN。手番が未決でも取れる。
     */
    "boardSfen": string;

    /**
     * SFEN は局面全体の SFEN。**手番が未決なら空**（決めていない手番を勝手に
     * 先手へ倒さないため。position.Position.SFEN と同じ理由）。
     */
    "sfen": string;

    /**
     * LabelSFEN は**画像のラベルとしての** SFEN。**局面が確定していなくても必ず入る。**
     * 
     * ⚠️ **表示にも解析にも使わないこと。** 用途は suteme への学習データ登録だけで、
     * 手番が未決でも `b` と書き、決まっているぶんの持ち駒を必ず載せる
     * （`position.Position.LabelSFEN` の注記を読むこと）。**画面に出すのは SFEN**。
     */
    "labelSfen": string;

    /**
     * LabelNotes は LabelSFEN を組み立てるために妥協した点（手番を先手にした・
     * 先後未決の持ち駒を落とした）。**送る前にユーザーへ出す**（黙って捨てない）。
     */
    "labelNotes": string[] | null;

    /**
     * Turn は 0=不明 / 1=先手番 / 2=後手番。
     */
    "turn": number;
    "turnLabel": string;

    /**
     * MoveNumber は手数。0 は不明。
     */
    "moveNumber": number;

    /**
     * Cells は 81 マス（SFEN 記述順。rank*9+file）。
     */
    "cells": EditCell[] | null;

    /**
     * Inventory は「存在するはずの駒」の在庫。**訂正 UI の駒箱はこれを並べる。**
     */
    "inventory": position$0.Stock[] | null;

    /**
     * Warnings は局面として成立していない点。**エラーではない**（直している最中は
     * 壊れていて当たり前）。
     */
    "warnings": string[] | null;

    /**
     * Dirty は認識結果から変更したか。「訂正を捨てて戻す」を出すかの判断に使う。
     */
    "dirty": boolean;
}

/**
 * EngineCheck は「接続を確認」の結果。
 * 
 * **エラーも値として返す**（error にしない）。設定タブに出す情報であって、
 * 呼び出しが失敗したわけではない。エンジンを置く前に確かめるのは普通の使い方。
 */
export interface EngineCheck {
    /**
     * Path は確かめた実行ファイル（同梱なら空）。
     */
    "path": string;

    /**
     * Builtin は同梱のエンジンか。
     */
    "builtin": boolean;

    /**
     * OK は繋がったか。
     */
    "ok": boolean;

    /**
     * Name は繋がったエンジンの名前（`id name`）。
     */
    "name": string;

    /**
     * Options はエンジンが宣言した option の数。
     */
    "options": number;

    /**
     * Applied は `isready` の前に送った `setoption` の数（**既定値を含む**）。
     * 
     * **送ったことが見えないと、効いているか確かめようがない**（option には
     * 応答が返らない）。宣言より少ないのが普通（button と空の既定値は送らない）。
     */
    "applied": number;

    /**
     * Error は繋がらなかった理由（日本語）。
     */
    "error": string;
}

/**
 * EngineSettings は解析に使う USI エンジンの設定。
 * 
 * **「外部エンジンを使うか」の真偽値は持たない。** パスが空なら同梱のエンジン、
 * 入っていれば外部エンジン。2 つ持つと「パスが入っているのに無効」という
 * 食い違いが起きる（ikkyoku.EngineConfig の注記と同じ）。
 */
export interface EngineSettings {
    /**
     * Path は USI エンジンの実行ファイル。空なら同梱。
     */
    "path": string;

    /**
     * Builtin は同梱のエンジンを使う状態か（Path が空）。**表示用。**
     * フロントで `path === ""` を判定させないため（判断の基準を Go 側に置く）。
     */
    "builtin": boolean;

    /**
     * OptionCount は config.json に書いた setoption の数。**表示用。**
     * 
     * option は画面に出していない（エンジンごとに違いすぎる）ので、
     * **書いたものが効いていることだけ**は見えるようにしておく。
     */
    "optionCount": number;
}

/**
 * FitResult はガイド枠の自動フィットの結果。
 * 
 * **見つからなかったことはエラーではない。** 盤が映っていない画面に枠を置いている
 * ことも、認識が外すこともある(設計原則3)。そのときは Fitted=false と理由を返し、
 * 枠は 1px も動かさない。error になるのはキャプチャ自体ができなかったときだけ。
 */
export interface FitResult {
    "fitted": boolean;
    "confidence": number;
    "message": string;
}

/**
 * GuideLayout は枠ウィンドウの描画寸法(CSS px)をフロントに渡すための型。
 */
export interface GuideLayout {
    "borderPx": number;
    "toolbarPx": number;
}

/**
 * RecognizerStatus は駒種推論器(suteme)の読み込み状況。
 */
export interface RecognizerStatus {
    /**
     * Source は読み込み元。設定で指定していなければ空(suteme 既定の探索に任せる)。
     */
    "source": string;
    "ready": boolean;
    "error": string;
}

/**
 * TrainingSendResult は登録の結果。
 */
export interface TrainingSendResult {
    "id": string;

    /**
     * Duplicate は同じ画像が既に登録されていたか。**失敗ではない**
     * （suteme は画像のハッシュで再送を弾き、既存の ID を返す）。
     */
    "duplicate": boolean;
    "entries": number;
}

/**
 * TrainingSettings は「訂正盤面を suteme に登録する」の設定。
 * 
 * **ikkyoku.TrainingConfig をそのまま返していない。** 画面に出すのは
 * 「実際に送る先(Target)」まで組み立てた形で、Host/Port の既定値の解決を
 * フロントに持たせないため(既定は training パッケージが持つ)。
 */
export interface TrainingSettings {
    "enabled": boolean;
    "host": string;
    "port": number;
    "token": string;

    /**
     * Target は上の設定から組み立てた接続先("http://host:port")。**表示用。**
     */
    "target": string;
}

/**
 * TrainingStatus は「今このサーバに送ってよいか」の問い合わせ結果。
 * 
 * **エラーも値として返す**（error にしない）。設定タブに出す情報であって、
 * 呼び出しが失敗したわけではない。相手が起動していないのは普通の状態。
 */
export interface TrainingStatus {
    /**
     * Configured は「訂正盤面を suteme に登録する」が有効か。
     */
    "configured": boolean;

    /**
     * Target は問い合わせ先("http://host:port")。
     */
    "target": string;

    /**
     * Reachable は応答があったか。
     */
    "reachable": boolean;

    /**
     * Error は応答が無い・受け付けられない場合の理由（日本語）。
     */
    "error": string;

    /**
     * Accepting は suteme 側で登録受付が有効になっているか。
     * 
     * ⚠️ **false でも、同じマシン（ループバック）からは送れる。** suteme は
     * ループバックを認証・受付判定の手前で素通しにしている。**送信の可否として
     * 使わないこと**（送れるのに送れないと表示することになる）。表示に留める。
     */
    "accepting": boolean;

    /**
     * Detailed 以下は、相手が素性を明かした場合だけ入る（ループバックか、
     * 正しいトークンを持っている場合）。
     */
    "detailed": boolean;
    "entries": number;
    "capacity": number;
    "dataVersion": string;

    /**
     * Note は「そのまま送れるとは限らない」ことを伝える補足（空なら無し）。
     */
    "note": string;
}
