// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PositionService は訂正中の局面を持つ Service。
 * 
 * **1 つだけ状態を持つ**（今直している局面）。ルートパッケージ側（`ikkyoku` /
 * `position`）は状態を持たない約束なので、「今どれを直しているか」というアプリの
 * 状態はここに置く。**検討セッションもいずれここに乗る**（今は 1 局面だけ）。
 * 
 * **永続化しない**（2026-08-07 決定）。メモリ上に持つだけで、保存はエクスポートの
 * 予定。1 時間で捨ててよい情報のために保存形式を先に決めない。
 * 
 * フロントとのやり取りは**毎回 EditState を返す**形にしてある。操作のたびに
 * 「盤・在庫・警告」を全部返せば、フロント側に局面の写しを持たなくて済む
 * （持つと、Go 側の盤とフロントの盤がずれたときに直しようがない）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FlipSide は駒の先後を入れ替える。
 */
export function FlipSide(rank: number, file: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(3089738494, rank, file);
}

/**
 * FromHand は駒台の駒を盤へ置く（駒台 → 盤のドラッグ＆ドロップ）。
 * **その側の駒台に無ければエラー**（見本から置く Place とはそこが違う）。
 */
export function FromHand(rank: number, file: number, piece: number, black: boolean): $CancellablePromise<$models.EditState> {
    return $Call.ByID(1528633255, rank, file, piece, black);
}

/**
 * Load は認識結果（盤面部分の SFEN）を読み込んで訂正を始める。
 * 
 * **撮るたびに呼ぶ。** 1 回のキャプチャは他と独立している（設計原則1）ので、
 * 前の訂正内容を引き継がない。壊れた盤面でも読めた分で始める（設計原則3）。
 */
export function Load(boardSFEN: string): $CancellablePromise<$models.EditState> {
    return $Call.ByID(741302310, boardSFEN);
}

/**
 * Move は盤の中で駒を動かす（盤 → 盤のドラッグ＆ドロップ）。
 */
export function Move(fromRank: number, fromFile: number, toRank: number, toFile: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(3103626707, fromRank, fromFile, toRank, toFile);
}

/**
 * Place は駒箱から盤へ置く（駒箱 → 盤のドラッグ＆ドロップ）。
 * 
 * **在庫が尽きていても置ける。** 余計な駒を外す前に正しい駒を置けないと詰むため
 * （position.Place の注記を参照）。上限超過は Warnings と在庫の負の値に出る。
 */
export function Place(rank: number, file: number, piece: number, black: boolean, promoted: boolean): $CancellablePromise<$models.EditState> {
    return $Call.ByID(1054658217, rank, file, piece, black, promoted);
}

/**
 * Remove はマスを空にする（盤 → 駒箱のドラッグ＆ドロップ）。
 * **認識が作った余計な駒を外す操作。** 先後は決めない（駒台の未割り当てに入る）。
 */
export function Remove(rank: number, file: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(876291842, rank, file);
}

/**
 * Reset は訂正を捨てて認識結果に戻す。
 */
export function Reset(): $CancellablePromise<$models.EditState> {
    return $Call.ByID(2471945417);
}

/**
 * SetHand は駒台のうち片側の枚数を n 枚にする。
 * **駒台の先後も盤面からは決まらない**ので、これも人間の入口。
 * ドラッグ以外の入口（未割り当てを一括で寄せる操作）として残してある。
 */
export function SetHand(piece: number, black: boolean, n: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(1543092003, piece, black, n);
}

/**
 * SetMoveNumber は手数を決める（0 は不明）。
 */
export function SetMoveNumber(n: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(1351221034, n);
}

/**
 * SetTurn は手番を決める（0=不明 / 1=先手番 / 2=後手番）。
 * 
 * **盤面からは決まらないので、ここが人間の入口。**
 */
export function SetTurn(turn: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(690227125, turn);
}

/**
 * State は今の状態を返す（何も変えない）。フロントの初期表示用。
 */
export function State(): $CancellablePromise<$models.EditState> {
    return $Call.ByID(280258907);
}

/**
 * ToHand は盤の駒を駒台へ移す（盤 → 先手/後手の駒台のドラッグ＆ドロップ）。
 * **外すのと先後を決めるのが 1 操作。**
 */
export function ToHand(rank: number, file: number, black: boolean): $CancellablePromise<$models.EditState> {
    return $Call.ByID(246306642, rank, file, black);
}

/**
 * TogglePromoted は成/不成を切り替える。
 */
export function TogglePromoted(rank: number, file: number): $CancellablePromise<$models.EditState> {
    return $Call.ByID(967915810, rank, file);
}
