// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService は設定ファイル(config.json)の読み書きを Wails にバインドする Service。
 * 
 * CaptureService と分けてあるのは、あちらが「撮る」ことの責務だから。設定は
 * 起動時にも読むので、**main() が最初に作って、読み込み済みの Config を配る**役でもある。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEngine は一覧にエンジンを 1 つ足す（**空のパスなら同梱エンジン**）。
 * 
 * **同じ実行ファイルを 2 つ登録できる。** option（置換表・スレッド数）を変えて
 * 比べるのは正当な使い方なので、パスの重複では断らない。
 */
export function AddEngine(path: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(590488953, path);
}

/**
 * BrowseEngine は実行ファイルを選ぶダイアログを出し、選ばれたものを一覧に**足す**。
 * 
 * 取り消したら何もしない。
 */
export function BrowseEngine(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1533817116);
}

/**
 * BrowseEngineFor は既存の登録の実行ファイルを**選び直す**（一覧の行の「参照…」）。
 * 
 * ⚠️ **BrowseEngine（追加）と混ぜないこと。** 差し替えのつもりで押したら
 * 登録が増えていた、という事故になる。
 */
export function BrowseEngineFor(id: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(843000435, id);
}

/**
 * MoveEngine は一覧の中で登録の位置を 1 つ動かす（delta は -1 で上、+1 で下）。
 * 
 * **並び順は表示の順序そのもの。** 解析タブのエンジンごとの結果も、評価値グラフの
 * 折れ線も、勝率バーが最初に出すエンジンも、この一覧の順で決まる。**同時に走らせて
 * 比べる**のが複数登録の目的なので、**よく見るものを上に置けること**は要る。
 * 
 * ⚠️ **並び順は「優先度」ではない。** 上のエンジンが正しいという意味も、
 * 先に走るという意味も無い（**解析は全部同時に走る**）。
 * 
 * ⚠️ **「解析に使う」を外した登録も含めた一覧の中で動かす。** 走るものだけを
 * 詰めて数えると、**チェックを外した瞬間に見えている順番と食い違う**。
 * 
 * 端から先へは動かさない（**回り込ませない**）。押しても何も起きないのは、
 * 一番上のものが一番下へ飛ぶより分かりやすい。
 */
export function MoveEngine(id: string, delta: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1981981495, id, delta);
}

/**
 * RemoveEngine は登録を消す。
 * 
 * **全部消すと同梱エンジン 1 つに戻る**（`ikkyoku.Config.EngineList`）。
 * 解析できない状態に落とし込まないため。
 */
export function RemoveEngine(id: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2761370694, id);
}

/**
 * ResetEngineOptions は設定した値を全部捨てて、エンジンの既定に戻す。
 * 
 * **宣言（`OptionSpecs`）は捨てない** —— 入力欄が作れなくなるので、
 * 戻す先が画面から消えてしまう。
 * 
 * ⚠️ **候補手の本数（`MultiPV`）も残す。** このボタンが並んでいるのは
 * 設定タブの option の一覧で、**そこに MultiPV は出ていない**（入口は解析タブ）。
 * 出ていないものを巻き添えで戻すと、**押した本人に何が起きたか分からない。**
 */
export function ResetEngineOptions(id: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2207888277, id);
}

/**
 * SetAnalyzeSeconds は「考える秒数」を保存する（解析タブの選択。**0 は無制限**）。
 * 
 * ⚠️ **0 も保存すること**（「無制限」は正当な選択）。`Config.AnalyzeSeconds` が
 * ポインタなのはこのため —— 値で持って省略すると、**次の起動で既定に戻る**。
 * 
 * ⚠️ **連続モードのチェックとは扱いが違う**（あちらは起動のたびに入で始まる
 * その場かぎりの操作）。秒数は待ち時間を決める値で、連続解析では
 * 「手数 × 秒数」がそのまま所要時間になるので、**選び直しを毎回やらせない。**
 */
export function SetAnalyzeSeconds(v: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1365801749, v);
}

/**
 * SetClickThrough は「枠の内側で後ろの画面を操作する」を切り替えて保存し、**その場で効かせる。**
 * 
 * 起動時まで待たせないのは、これが**中継を触りたくなったその瞬間に切り替える**設定だから
 * （「起動時に盤面を探す」とはそこが違う）。
 * 
 * ⚠️ **保存できたときだけ効かせること。** 先に効かせると、保存に失敗したときに
 * 「画面のチェックは外れているのに枠は素通しのまま」になる。
 */
export function SetClickThrough(v: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(731904781, v);
}

/**
 * SetEngineColor は評価値グラフの折れ線の色を決める（空にすると既定色に戻る）。
 * 
 * **入口は解析タブのエンジンの見出し**（候補手を出しているところ）。設定タブでは
 * なくそこに置いてあるのは、**色を変えたくなるのは折れ線と結果を見比べている
 * 最中**だから。
 * 
 * ⚠️ **色は登録に紐づく**（一覧の何番目か、ではない）。並べ替えたり 1 つ
 * 外したりしても色が動かないので、**前に見ていた線と同じ色が別のエンジンを
 * 指すことがない**。
 */
export function SetEngineColor(id: string, color: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1091215457, id, color);
}

/**
 * SetEngineEnabled は「解析に使う」を切り替える。
 * 
 * **外しても登録は消えない。** エンジンを入れ替えて比べる作業では、外したものを
 * また戻すことが多い。
 */
export function SetEngineEnabled(id: string, enabled: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(632833467, id, enabled);
}

/**
 * SetEngineMultiPV は候補手の本数を決める（解析タブのエンジンの見出し）。
 * 
 * **入口をそこに置いてあるのが要点**（2026-08-15。以前は解析の行に**全エンジン
 * 共通**の欄が 1 つあった）。本数を変えたくなるのは**候補手を読んでいる最中**で、
 * しかも**どれくらい出すかはエンジンごとに変えたい**（速いエンジンは多めに、
 * 重いエンジンは 1 本、など）。
 * 
 * ⚠️ **保存先は `Options["MultiPV"]`**（エンジンが宣言している option そのもの）。
 * 専用の欄を作らないのは、**同じ値の置き場所を 2 つ持たない**ため。
 * 
 * ⚠️ **繋ぎ直しは要らない。** これは探索ごとに送る option なので、
 * `AnalyzeService.engineKey`（接続の指紋）からは外してある。
 */
export function SetEngineMultiPV(id: string, n: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3386769369, id, n);
}

/**
 * SetEngineName は表示名を付ける（空にすると既定の名前に戻る）。
 * 
 * **同じ exe を option 違いで 2 つ登録したときに、どちらか分かるようにするため。**
 * エンジンが `id name` で名乗る名前は繋がないと分からないので、それとは別に要る。
 */
export function SetEngineName(id: string, name: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2068350557, id, name);
}

/**
 * SetEngineOption は `setoption` で送る値を 1 つ決める（設定タブのエンジンの行）。
 * 
 * **空文字にすると設定から消え、エンジンが宣言した既定値に戻る**（＝送られるのは
 * 既定値。`core/usi/client.plannedOptions`）。⚠️ **既定と同じ値を書き込んだときも
 * 消す** —— 書き残すと「エンジンの既定に従う」という指定ができなくなり、
 * **エンジンのバージョンが上がって既定が変わっても古い値で固まる**（しかも
 * 画面では気づけない）。
 * 
 * ⚠️ **値の検分は宣言があるときだけ。** 宣言に無い名前も受ける（宣言していない
 * option を受け付けるエンジンがあり、**設定ファイルを手で編集する経路を塞がない**）。
 * 
 * ⚠️ **`isready` の前にしか効かない option なので、繋ぎ直しが要る。** 判断は
 * `AnalyzeService.engineKey`（パス + options の指紋）が持っているので、
 * **ここで接続を触らないこと。**
 */
export function SetEngineOption(id: string, name: string, value: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3103718499, id, name, value);
}

/**
 * SetEnginePath は登録済みエンジンの実行ファイルを差し替える。
 * 
 * **空にするとその登録は同梱のエンジンになる**（登録そのものは消えない）。
 */
export function SetEnginePath(id: string, path: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1535611797, id, path);
}

/**
 * SetFitOnStartup は「起動時に盤面を探す」を切り替えて保存する。
 */
export function SetFitOnStartup(v: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2836646091, v);
}

/**
 * SetPonanzaConstant は勝率の変換に使う定数を保存する（解析タブの勝率バー）。
 * 
 * **0 以下なら既定に戻す**（設定ファイルからも消える）。欄を空にしたときの
 * 素直な意味が「既定でよい」なので、そこでエラーにしない。
 */
export function SetPonanzaConstant(v: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4145834603, v);
}

/**
 * SetTraining は「訂正盤面を suteme に登録する」の設定を保存する。
 * 
 * **接続の確認はしない。** 設定を保存する操作と、相手が受け付けているかを見る操作
 * (TrainingService.Status)は別。書けないサーバでも設定は保存できたほうがよい
 * (先に設定を入れてから suteme を起動する、という順序が普通にある)。
 */
export function SetTraining(enabled: boolean, host: string, port: number, token: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(798401026, enabled, host, port, token);
}

/**
 * Settings は設定タブに出す値を返す。
 */
export function Settings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(126564865);
}
