// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService は設定ファイル(config.json)の読み書きを Wails にバインドする Service。
 * 
 * CaptureService と分けてあるのは、あちらが「撮る」ことの責務だから。設定は
 * 起動時にも読むので、**main() が最初に作って、読み込み済みの Config を配る**役でもある。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseEngine は実行ファイルを選ぶダイアログを出し、選ばれたパスを保存する。
 * 
 * **パスを手で打たせない。** 将棋エンジンは深いディレクトリに置かれることが多く、
 * 打ち間違いが一番起きやすい入口。取り消したら何もしない(空文字が返る)。
 */
export function BrowseEngine(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1533817116);
}

/**
 * SetEnginePath は解析に使う USI エンジンの実行ファイルを保存する。
 * 
 * **空にすると同梱のエンジンに戻る。**
 * 
 * ⚠️ **起動して繋がるかは確かめない。** 設定を保存する操作と、実際に繋がるかを見る
 * 操作(AnalyzeService.CheckEngine)は別にしてある。まだ置いていないパスを先に
 * 書いておく、という順序が普通にあるため(接続設定と同じ考え方)。
 * 
 * 存在の確認だけはする。**打ち間違いは「解析を押したら繋がらない」より、
 * ここで分かるほうが早い。**
 */
export function SetEnginePath(path: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1535611797, path);
}

/**
 * SetFitOnStartup は「起動時に盤面を探す」を切り替えて保存する。
 */
export function SetFitOnStartup(v: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2836646091, v);
}

/**
 * SetTraining は「訂正盤面を suteme に登録する」の設定を保存する。
 * 
 * **接続の確認はしない。** 設定を保存する操作と、相手が受け付けているかを見る操作
 * (TrainingService.Status)は別。書けないサーバでも設定は保存できたほうがよい
 * (先に設定を入れてから suteme を起動する、という順序が普通にある)。
 */
export function SetTraining(enabled: boolean, host: string, port: number, token: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(798401026, enabled, host, port, token);
}

/**
 * Settings は設定タブに出す値を返す。
 */
export function Settings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(126564865);
}
