// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService は設定ファイル(config.json)の読み書きを Wails にバインドする Service。
 * 
 * CaptureService と分けてあるのは、あちらが「撮る」ことの責務だから。設定は
 * 起動時にも読むので、**main() が最初に作って、読み込み済みの Config を配る**役でもある。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEngine は一覧にエンジンを 1 つ足す（**空のパスなら同梱エンジン**）。
 * 
 * **同じ実行ファイルを 2 つ登録できる。** option（置換表・スレッド数）を変えて
 * 比べるのは正当な使い方なので、パスの重複では断らない。
 */
export function AddEngine(path: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(590488953, path);
}

/**
 * BrowseEngine は実行ファイルを選ぶダイアログを出し、選ばれたものを一覧に**足す**。
 * 
 * 取り消したら何もしない。
 */
export function BrowseEngine(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1533817116);
}

/**
 * BrowseEngineFor は既存の登録の実行ファイルを**選び直す**（一覧の行の「参照…」）。
 * 
 * ⚠️ **BrowseEngine（追加）と混ぜないこと。** 差し替えのつもりで押したら
 * 登録が増えていた、という事故になる。
 */
export function BrowseEngineFor(id: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(843000435, id);
}

/**
 * MoveEngine は一覧の中で登録の位置を 1 つ動かす（delta は -1 で上、+1 で下）。
 * 
 * **並び順は表示の順序そのもの。** 解析タブのエンジンごとの結果も、評価値グラフの
 * 折れ線も、勝率バーが最初に出すエンジンも、この一覧の順で決まる。**同時に走らせて
 * 比べる**のが複数登録の目的なので、**よく見るものを上に置けること**は要る。
 * 
 * ⚠️ **並び順は「優先度」ではない。** 上のエンジンが正しいという意味も、
 * 先に走るという意味も無い（**解析は全部同時に走る**）。
 * 
 * ⚠️ **「解析に使う」を外した登録も含めた一覧の中で動かす。** 走るものだけを
 * 詰めて数えると、**チェックを外した瞬間に見えている順番と食い違う**。
 * 
 * 端から先へは動かさない（**回り込ませない**）。押しても何も起きないのは、
 * 一番上のものが一番下へ飛ぶより分かりやすい。
 */
export function MoveEngine(id: string, delta: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1981981495, id, delta);
}

/**
 * RemoveEngine は登録を消す。
 * 
 * **全部消すと同梱エンジン 1 つに戻る**（`ikkyoku.Config.EngineList`）。
 * 解析できない状態に落とし込まないため。
 */
export function RemoveEngine(id: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2761370694, id);
}

/**
 * SetEngineEnabled は「解析に使う」を切り替える。
 * 
 * **外しても登録は消えない。** エンジンを入れ替えて比べる作業では、外したものを
 * また戻すことが多い。
 */
export function SetEngineEnabled(id: string, enabled: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(632833467, id, enabled);
}

/**
 * SetEngineName は表示名を付ける（空にすると既定の名前に戻る）。
 * 
 * **同じ exe を option 違いで 2 つ登録したときに、どちらか分かるようにするため。**
 * エンジンが `id name` で名乗る名前は繋がないと分からないので、それとは別に要る。
 */
export function SetEngineName(id: string, name: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2068350557, id, name);
}

/**
 * SetEnginePath は登録済みエンジンの実行ファイルを差し替える。
 * 
 * **空にするとその登録は同梱のエンジンになる**（登録そのものは消えない）。
 */
export function SetEnginePath(id: string, path: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1535611797, id, path);
}

/**
 * SetFitOnStartup は「起動時に盤面を探す」を切り替えて保存する。
 */
export function SetFitOnStartup(v: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2836646091, v);
}

/**
 * SetPonanzaConstant は勝率の変換に使う定数を保存する（解析タブの勝率バー）。
 * 
 * **0 以下なら既定に戻す**（設定ファイルからも消える）。欄を空にしたときの
 * 素直な意味が「既定でよい」なので、そこでエラーにしない。
 */
export function SetPonanzaConstant(v: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4145834603, v);
}

/**
 * SetTraining は「訂正盤面を suteme に登録する」の設定を保存する。
 * 
 * **接続の確認はしない。** 設定を保存する操作と、相手が受け付けているかを見る操作
 * (TrainingService.Status)は別。書けないサーバでも設定は保存できたほうがよい
 * (先に設定を入れてから suteme を起動する、という順序が普通にある)。
 */
export function SetTraining(enabled: boolean, host: string, port: number, token: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(798401026, enabled, host, port, token);
}

/**
 * Settings は設定タブに出す値を返す。
 */
export function Settings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(126564865);
}
