// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StudyService は**確定した局面**を持つ Service（解析タブ）。
 * 
 * ⚠️ **PositionService とは別の局面を持つ。同じものを 2 つの意味で使わない。**
 * 
 * 	PositionService … 訂正タブ。認識の誤りを直す面。**合法性を問わない**自由編集で、
 * 	                  手番も駒台の先後も未決でよい。**画像に見えたとおりの盤**
 * 	StudyService    … 解析タブ。手を選んで局面を進める面。**確定した局面が根**で、
 * 	                  ここから先は合法手だけを辿る（手を進める UI は次段）
 * 
 * 受け渡しは `Adopt`（訂正タブの「この局面を解析する」）の 1 か所だけ。**写しを取る**
 * ので、採ったあとに訂正タブ側をいじってもこちらは動かない（動くと、解析結果が
 * どの局面の値なのか分からなくなる）。
 * 
 * **戻れる。** 訂正タブへ戻って直し、もう一度 `Adopt` すればよい。そのとき前の
 * 手順と解析結果は捨てる（別の局面の話になるため）。捨てるのはフロントではなく
 * ここが `Adopt` のたびに根ごと入れ替えることで担保する。
 * 
 * **永続化しない**（PositionService と同じ。2026-08-07 決定）。検討セッションは
 * メモリ上に持つだけで、保存は明示的なエクスポート。
 * 
 * **手順はここに乗る**（2026-08-11）。`position.Study` が「根 + 指した手の並び」を
 * 持ち、合法手は `ikkyoku/legal`（engine）が出す。⚠️ **`ikkyoku → engine` の Go 依存が
 * ここで戻るが、解析だけは USI 経由のまま**にすること（棋力の問題を設定の問題にした
 * 意味が無くなる）。**用途が違う** —— こちらは手の検証であって解析ではない。
 * 
 * **手順は木**（2026-08-13）。戻って別の手を指すと**枝が生える**（前の手順は消えない）。
 * 木の形の最終形は `core/kifu` が持てるようになってから決める（`position` に仮置き）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLine は解析の候補手（読み筋）を**枝として木に足す**（候補手の右クリック）。
 * 
 * ⚠️ **押しても指さない**（＝今見ている局面は動かない）。動くと走っている解析が
 * 別の局面のものになり、**候補を続けて足せない**。
 * 
 * ⚠️ **候補の頭が本譜と同じなら枝を増やさず、食い違うところで枝にする**
 * （判断は `position.Study.AddLine`。**フロントで突き合わせないこと**）。
 * 
 * engineID は**その読み筋を出したエンジン**の登録 ID。手順リストで
 * **誰が言った手なのか**を色で出すのに使う（`Node.Sources`）。
 * ⚠️ **空でも足せること** —— 出所が分からない読み筋でも、手順に足す価値は変わらない。
 */
export function AddLine(engineID: string, moves: string[] | null): $CancellablePromise<$models.AddLine> {
    return $Call.ByID(4171557245, engineID, moves);
}

/**
 * Adopt は訂正タブの局面を採って、解析タブの根にする。
 * 
 * ⚠️ **確定していない局面は採らない。** 手番か駒台の先後が未決だと
 * `position.Position.SFEN()` がエラーを返すので、そのまま理由として返す。
 * ここで先手に倒すと、決めていない手番でエンジンが読むことになる（設計原則5）。
 * **これは警告ではなくエラー** —— 決めてもらう以外に手が無い。
 */
export function Adopt(): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(1565567598);
}

/**
 * Branch はその手から先を**本譜ではなく変化にする**（手順リストの右クリック →
 * 「分岐にする」。2026-08-14）。
 * 
 * **本譜の先端から試しに指した手を、エンジンの読み筋と同じ扱いに落とす操作。**
 * 手順リストでは 1 段下がって**前の手にぶら下がり**、畳めるようになる。
 * 
 * ⚠️ **手順は 1 手も消えない**（`DropFrom` と混同しないこと）。**見ている局面も
 * 動かない** —— 見え方が変わるだけなので、盤まで動くと何が起きたのか分からない。
 * 
 * ⚠️ **評価値も捨てない。** 節点はそのまま（id も変わらない）で、
 * **本譜かどうかが変わるだけ**。
 */
export function Branch(id: number): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(240092428, id);
}

/**
 * Clear は解析タブを空に戻す。**撮り直したときに呼ぶ** —— 前の局面の盤と
 * 評価値が新しい認識結果の裏で生き残っていると、どちらが今の話か分からなくなる。
 */
export function Clear(): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(1191545465);
}

/**
 * DropFrom はその手**とその先（子孫の枝も全部）**を消す（**手順リストの右クリック**）。
 * 
 * ⚠️ **「1手戻す」は無くなった**（2026-08-13）。**消す量を手そのもので指す**形に
 * してある —— `Undo` は「今どこを見ているか」に依存していたので、戻って見ている
 * 最中に押すと何が消えるのか分かりにくかった。今は**押した手から下**で、
 * 画面の見た目とそのまま一致する。
 * 
 * **枝も本譜も同じように消せる**（本譜は URL から取り直せる）。
 * **見るだけなら GoTo。混同しないこと**（あちらは何も消さない）。
 * 
 * ⚠️ **引数は節点の id で、手数ではない**（枝があると同じ手数が何個もある）。
 */
export function DropFrom(id: number): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(2906104777, id);
}

/**
 * Evals は評価値グラフの中身を返す（解析タブ）。
 * 
 * **フロントはこれを描くだけ。** 点の並びも横軸の範囲を決める材料もここが返すので、
 * **フロント側で `StudyState` と突き合わせて計算しないこと**
 * （2 つの値が別のタイミングで届くぶんだけずれる）。
 * 
 * ⚠️ **エンジンごとに別の折れ線。** 合成しない（平均も多数決も取らない）。
 */
export function Evals(): $CancellablePromise<$models.EvalGraph> {
    return $Call.ByID(1726375459);
}

/**
 * GoTo はその節点の局面を見る（0 なら根）。**手順は消さない。**
 * 
 * ⚠️ **引数は節点の id で、手数ではない。**
 */
export function GoTo(id: number): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(2871148087, id);
}

/**
 * LoadKifu は KIF テキストを読んで解析タブの根と手順にする。
 * 
 * ⚠️ **訂正タブを経由しない 2 つめの入口。** 「受け渡しは Adopt の 1 か所だけ」は
 * **訂正タブとの受け渡し**の話で、入力の口が増えること自体は想定どおり
 * （画像は認識を通るので訂正タブへ、KIF は既に確定しているので直接ここへ）。
 * **`PositionService` は触らない** —— 撮った局面を消してしまうと、
 * 貼り付けたのが誤りだったときに戻る先が無くなる。
 * 
 * **指し手が全て反映された状態**（最終手まで進めた局面）で返す。戻って見たければ
 * 手順のリストから辿れる。
 */
export function LoadKifu(text: string): $CancellablePromise<$models.KifuLoad> {
    return $Call.ByID(2011736629, text);
}

/**
 * LoadKifuURL は URL から棋譜を取ってきて読み込む（`LoadKifu` の口違い）。
 * 
 * **取ってくるのは `ikkyoku/kifuweb`**（文字コードの判別もあちら。日本将棋連盟の
 * 棋譜中継は Shift_JIS）。ここは繋ぐだけで、**取得も KIF の解釈もここに書かない。**
 */
export function LoadKifuURL(rawURL: string): $CancellablePromise<$models.KifuLoad> {
    return $Call.ByID(324395342, rawURL);
}

/**
 * NewGame は何もないところから対局を始める（入力タブの「新しく対局を始める」）。
 * 
 * ⚠️ **訂正タブを経由しない 3 つめの入口**（画像 → 訂正タブ、棋譜 → ここ、新規 → ここ）。
 * 棋譜と同じ扱いなのは、**初期局面が手合割で一意に決まる**から（直すものが無い）。
 * **`PositionService` は触らない** —— 撮った局面を消してしまうと、
 * 新しく始めたのが誤操作だったときに戻る先が無くなる。
 * 
 * ⚠️ **戻り値の型を棋譜の読み込みと共有しているのは、フロントの描き方が同じだから**
 * （根を入れ替えて解析タブを開き、1 行の説明を出す）。**別の経路を作らないこと。**
 * 
 * ⚠️ **「自分がどちら側か」はここでは受けない。** 今それが決めているのは
 * **画面の向き（視点）だけ**で、局面には一切効かない（平手の初期局面は
 * どちらを持っても同じ）。対局モード（人が片側を持ち、エンジンがもう片側を指す）を
 * 入れる段になったら、その時点でここに載せる。**先回りして未使用の欄を作らない。**
 */
export function NewGame(handicap: string): $CancellablePromise<$models.KifuLoad> {
    return $Call.ByID(4088092144, handicap);
}

/**
 * Play は 1 手指して局面を進める（解析タブの盤のクリック）。
 * 
 * ⚠️ **合法手だけ。** 訂正タブ（どこへでも動かせる）とは別の面で、ここは実際の
 * 対局と同じように進める。指せない手は Go 側で断る（**フロントで同じ判定を
 * 書かないこと** —— 合法手の一覧は `StudyState.Legal` に出しているので、
 * 画面はそれを光らせるだけでよい）。
 * 
 * ⚠️ **戻って見ている途中で別の手を指すと、枝が生える**（2026-08-13。前の手順は
 * **消えない**）。**評価値も捨てない** —— 記録は節点に紐づいているので、
 * 枝を選び直せばそちらの折れ線がそのまま出る。
 */
export function Play(move: string): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(3489214574, move);
}

/**
 * ReloadKifu は取得元の URL から棋譜を取り直して、**URL の側を正**にする
 * （解析タブの手順の見出しの「再読み込み」。2026-08-13）。
 * 
 * 中継の .kif は 1 手進むたびに書き換わるので、**同じ URL をもう一度読んで
 * 手順を最新にする**のがこの口。⚠️ **入力タブから読み直させないこと** ——
 * あちらを通ると `LoadKifu` が根ごと入れ替えるので、**評価値が全部消える。**
 * 
 * # 何を残して何を捨てるか
 * 
 * **食い違ったところから先だけを差し替える。**
 * 
 * 	根が違う                … 別の対局なので全部捨てる（`LoadKifu` と同じ）
 * 	手順の頭が一致している    … 一致している範囲の**解析結果はそのまま残す**
 * 	途中から食い違う          … **その先は捨てて URL のものにする**（URL が正）
 * 
 * ⚠️ **「捨てる」で済んでいるのは分岐ツリーがまだ無いから。** 木が入ったら、
 * ここは**捨てるのではなく別の枝として残す**ことになる（`TODO.md` の「本譜のロック」。
 * 本譜は URL が更新し続け、分岐は手入力、という使い方が一番よくある）。
 * **そのときに直す場所はここ 1 か所**にしてある。
 * 
 * ⚠️ **食い違いが無ければ `dropAfter` を呼ばないこと。** あれは世代（epoch）を
 * 進めるので、**走っている解析の途中経過が捨てられる**（1 手進むたびに
 * 再読み込みする使い方では、毎回それが起きる）。
 */
export function ReloadKifu(): $CancellablePromise<$models.KifuLoad> {
    return $Call.ByID(1008325372);
}

/**
 * State は今の状態を返す（何も変えない）。フロントの初期表示用。
 */
export function State(): $CancellablePromise<$models.StudyState> {
    return $Call.ByID(15823641);
}
