// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrainingService は訂正した局面を suteme の学習用サーバへ登録する Service。
 * 
 * **状態を持たない。** 「今どの画像・どの局面か」はフロントが持っている
 * （撮った結果と EditState）ので、送るときにまとめて渡してもらう。ここが
 * 「直近の 1 枚」を覚えると、撮り直しとの食い違いを自分で管理することになる。
 * 
 * **自動では送らない**（2026-08-07 の決定）。人間が直したのは 1 マスで残り 80 マスは
 * 推論結果のまま、という「自分の出力を正解として食う」形になり、間違いが固定される。
 * 送るのは局面ごとにボタンを押したときだけ。
 * 
 * ⚠️ **画面に見えていない駒を知識で補った訂正は送らないこと**（テロップで盤が
 * 隠れている等）。ラベルが画素と一致しなくなる。これも自動送信にしない理由。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Send は訂正した局面を学習データとして登録する。
 * 
 * 渡すのは撮った PNG のパス・正解の SFEN・**画像の中での盤面の矩形**の 3 点。
 * これが suteme の学習サンプルの単位そのもので、81 マスの切り出しは向こうが行う
 * （**ikkyoku がサンプルの形式を知らないでいられる**のが要点）。
 * 
 * ⚠️ **矩形は認識結果の Debug.Region をそのまま渡すこと。** 盤の位置が分からないと
 * suteme は DetectBoard に頼ることになり、ずらしによる水増しも作れないため
 * 学習価値が落ちる（向こうは座標なしを 400 で断る）。
 */
export function Send(path: string, sfen: string, x1: number, y1: number, x2: number, y2: number): $CancellablePromise<$models.TrainingSendResult> {
    return $Call.ByID(3915639241, path, sfen, x1, y1, x2, y2);
}

/**
 * Status は suteme が登録を受け付けられる状態かを問い合わせる（設定タブの「確認」）。
 */
export function Status(): $CancellablePromise<$models.TrainingStatus> {
    return $Call.ByID(2343561945);
}
