// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../../../image/models.js";

/**
 * CellCategory はマスの大分類。
 * 
 * **「手前（上向き）＝先手」は規約であり、固定する。反転する設定は作らない。**
 * 駒の向きで分かるのは「どちらの対局者の駒か」だけで、その人が先手か後手かは
 * 盤の絵に写っていない（中継・紙面は「手前が先手」だが、ゲーム画面では
 * 自分が後手番のとき手前が後手になる）。**画像認識では原理的に解けないので
 * 解かない。** 呼び出し側が手前を先手として表現した SFEN を渡す責任を持つ。
 * 詳細は CLAUDE.md「先後の割り当ては『手前が先手』で固定（規約）」。
 */
export enum CellCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * 空
     */
    CellEmpty = 0,

    /**
     * 上向き。手前側の対局者の駒 → 先手として扱う
     */
    CellPieceUp = 1,

    /**
     * 下向き。奥側の対局者の駒 → 後手として扱う
     */
    CellPieceDown = 2,
};

/**
 * CellDebug はマス1つ分の認識過程。
 */
export interface CellDebug {
    /**
     * 0 = 上段（後手側）
     */
    "row": number;

    /**
     * 0 = 左（9筋）
     */
    "col": number;

    /**
     * Rect は切り出しに使った矩形（ExtractCell の 15% 拡張は含まない）。
     */
    "rect": image$0.Rectangle;

    /**
     * Category は最終的に採用した 空/先手/後手（0=空 / 1=先手 / 2=後手）。
     */
    "category": CellCategory;

    /**
     * OrientBy は向きの決め方。既定（分類器の幅プロファイル）では ""、
     * 分類器の確信度が足りず回転照合で決め直したときだけ "match"。
     */
    "orient_by"?: string;

    /**
     * Class は Predictor が返した駒種クラス（推論しなかったら -1、
     * ClassEmpty なら分類を覆して空にしたということ）。
     */
    "class": number;

    /**
     * Confidence は Predictor が返した確信度。
     */
    "confidence": number;

    /**
     * Piece は最終的に採用した SFEN 表記（空マスなら ""）。
     */
    "piece": string;
}

/**
 * Debug は認識1回分の観測情報。
 */
export interface Debug {
    /**
     * ImageBounds は入力画像の範囲。
     */
    "image_bounds": image$0.Rectangle;

    /**
     * Region は盤面と判定した外枠の矩形。マス割りはこれを9等分したもの。
     */
    "region": image$0.Rectangle;

    /**
     * RegionSource は Region の決め方。
     */
    "region_source": RegionSource;

    /**
     * Confidence は ValidateBoard の値（Result.Confidence と同じ）。
     * **RegionFromOption のときはゲートに使っていない**（手動指定は検証せず
     * そのまま使う）ので、低くても領域はその座標のまま。
     */
    "confidence": number;

    /**
     * BoardColor は盤の地色（分類の基準にした輝度の中央値）。
     */
    "board_color": number;

    /**
     * Predictor は使った駒種推論器。
     */
    "predictor": PredictorDebug;

    /**
     * Cells は81マスの認識過程（行優先）。
     */
    "cells": CellDebug[] | null;
}

/**
 * PredictorDebug は駒種推論器の素性。
 */
export interface PredictorDebug {
    /**
     * Kind は "knn" / "nn" / それ以外は Go の型名。
     */
    "kind": string;

    /**
     * Source は読み込み元のファイルパス（SetPredictor / WithPredictor で
     * 直接渡された場合は空）。
     */
    "source"?: string;

    /**
     * Detail は種別ごとの補足（k-NN なら "k=5, samples=4455"）。
     */
    "detail"?: string;
}

/**
 * RegionSource は盤面領域をどうやって決めたか。
 */
export enum RegionSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * RegionFromOption は WithRegion / WithRect による明示指定。
     * **この場合 ValidateBoard の値でゲートしていない**ので、
     * Confidence が低くても領域はそのまま使われる。
     */
    RegionFromOption = "option",

    /**
     * RegionFromDetect は DetectBoard による検出。
     */
    RegionFromDetect = "detect",

    /**
     * RegionFromWholeImage は「画像全体が盤面」フォールバック
     * （盤だけを切り出した画像でグリッド線が画像端に来る場合）。
     */
    RegionFromWholeImage = "whole",
};
