// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as suteme$0 from "../../suteme/models.js";

/**
 * Debug は認識1回分の観測情報(盤面と判定した矩形・その決め方・使った推論器・
 * マスごとの分類と確信度)。**Option と同じくエイリアスで、包み直さない。**
 * 矩形もクラスも suteme が出した値そのものなので、ikkyoku 側で同じ形の型を
 * 定義し直すと変換のぶんだけ嘘が入る余地が増える。
 * 
 * 用途は「認識が外れたときの切り分け」。撮った画像に Region と Cells[].Rect を
 * 重ねれば、座標がずれているのか駒種を外しているのかが一目で分かる。
 * **認識の判断には使わない**(あくまで観測用)。
 */
export type Debug = suteme$0.Debug;
