// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Node は手順ツリーの 1 手（**表示と `GoTo` の単位**）。
 * 
 * ⚠️ **木の写しであって、木そのものではない。** 親子は `ID`/`Parent` で辿る。
 */
export interface Node {
    /**
     * ID は節点の識別子（1 から。**0 は根の局面**）。
     * 
     * ⚠️ **手数ではない。** 枝があると同じ手数の節点が何個もあるので、
     * 「どの局面か」を指せるのは id だけ。
     */
    "id": number;

    /**
     * Parent は親の ID（**根の直後なら 0**）。
     */
    "parent": number;

    /**
     * Number は根からの手数（1 が根の次の手）。**画面に出すのは棋譜の手数**なので、
     * 呼び出し側が根の手数を足す（`StudyState.First`）。
     */
    "number": number;

    /**
     * USI は手文字列（"7g7f"）。**エンジンに渡すのはこれ。**
     */
    "usi": string;

    /**
     * Text は日本語表記（"▲７六歩"）。**画面に出すのはこちら。**
     * 
     * ⚠️ **変換に失敗しても USI がそのまま入る**（設計原則3）。手順そのものは
     * 正しいのに、表記の都合で手が消えるほうが困る。
     */
    "text": string;

    /**
     * Depth は枝の深さ（**本譜だけを辿ってきたら 0**）。ツリービューの字下げ。
     */
    "depth": number;

    /**
     * Main は親の最初の子か（＝その分岐での本筋）。
     */
    "main": boolean;
}

/**
 * Stock は駒種 1 つぶんの在庫。
 */
export interface Stock {
    /**
     * Piece はベース駒コード（sfen.Pawn など）。
     */
    "piece": number;

    /**
     * Letter は SFEN の大文字（"P"）。フロントが駒を描くのに使う。
     */
    "letter": string;

    /**
     * Name は日本語名（"歩"）。
     */
    "name": string;

    /**
     * Limit は先後合計の上限枚数。**これが「存在するはず」の総数。**
     */
    "limit": number;

    /**
     * Black / White は盤上の枚数（成駒はベース駒に合算）。
     */
    "black": number;
    "white": number;

    /**
     * Rest は残り = Limit - 盤上。**負なら過剰**（認識が余計な駒を作った状態）。
     * 正の値はそのまま「駒台にあるはずの枚数」（先後の区別は付かない）。
     */
    "rest": number;

    /**
     * HandBlack / HandWhite は Rest のうち先後に割り振った枚数。
     */
    "handBlack": number;
    "handWhite": number;

    /**
     * Unassigned は Rest のうち**まだ先後を決めていない**枚数。
     * **これが残っているあいだ局面は確定しない**（SFEN が書けない）。
     */
    "unassigned": number;
}
