// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Move は手順の 1 手。
 */
export interface Move {
    /**
     * Number は棋譜の数え方の手数（1 が初手）。**SFEN の手数とは 1 ずれる。**
     */
    "number": number;

    /**
     * USI は手文字列（"7g7f"）。**エンジンに渡すのはこれ。**
     */
    "usi": string;

    /**
     * Text は日本語表記（"▲７六歩"）。**画面に出すのはこちら。**
     * 
     * ⚠️ **変換に失敗しても USI がそのまま入る**（設計原則3）。手順そのものは
     * 正しいのに、表記の都合で手が消えるほうが困る。
     */
    "text": string;
}

/**
 * Stock は駒種 1 つぶんの在庫。
 */
export interface Stock {
    /**
     * Piece はベース駒コード（sfen.Pawn など）。
     */
    "piece": number;

    /**
     * Letter は SFEN の大文字（"P"）。フロントが駒を描くのに使う。
     */
    "letter": string;

    /**
     * Name は日本語名（"歩"）。
     */
    "name": string;

    /**
     * Limit は先後合計の上限枚数。**これが「存在するはず」の総数。**
     */
    "limit": number;

    /**
     * Black / White は盤上の枚数（成駒はベース駒に合算）。
     */
    "black": number;
    "white": number;

    /**
     * Rest は残り = Limit - 盤上。**負なら過剰**（認識が余計な駒を作った状態）。
     * 正の値はそのまま「駒台にあるはずの枚数」（先後の区別は付かない）。
     */
    "rest": number;

    /**
     * HandBlack / HandWhite は Rest のうち先後に割り振った枚数。
     */
    "handBlack": number;
    "handWhite": number;

    /**
     * Unassigned は Rest のうち**まだ先後を決めていない**枚数。
     * **これが残っているあいだ局面は確定しない**（SFEN が書けない）。
     */
    "unassigned": number;
}
