// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stock は駒種 1 つぶんの在庫。
 */
export interface Stock {
    /**
     * Piece はベース駒コード（sfen.Pawn など）。
     */
    "piece": number;

    /**
     * Letter は SFEN の大文字（"P"）。フロントが駒を描くのに使う。
     */
    "letter": string;

    /**
     * Name は日本語名（"歩"）。
     */
    "name": string;

    /**
     * Limit は先後合計の上限枚数。**これが「存在するはず」の総数。**
     */
    "limit": number;

    /**
     * Black / White は盤上の枚数（成駒はベース駒に合算）。
     */
    "black": number;
    "white": number;

    /**
     * Rest は残り = Limit - 盤上。**負なら過剰**（認識が余計な駒を作った状態）。
     * 正の値はそのまま「駒台にあるはずの枚数」（先後の区別は付かない）。
     */
    "rest": number;

    /**
     * HandBlack / HandWhite は Rest のうち先後に割り振った枚数。
     */
    "handBlack": number;
    "handWhite": number;

    /**
     * Unassigned は Rest のうち**まだ先後を決めていない**枚数。
     * **これが残っているあいだ局面は確定しない**（SFEN が書けない）。
     */
    "unassigned": number;
}
