// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Move は指せる手 1 つ。**盤の座標は position.Board と同じ数え方**
 * （rank=0 が一段目、file=0 が 9 筋）なので、UI 側で読み替えないこと。
 */
export interface Move {
    /**
     * USI は手文字列（"7g7f" / "7g7f+" / "P*5e"）。**エンジンに渡すのはこれ。**
     */
    "usi": string;

    /**
     * FromRank / FromFile は移動元。**打ちのときは -1。**
     */
    "fromRank": number;
    "fromFile": number;

    /**
     * Drop は打つ駒のベース駒コード（`sfen.Pawn` など）。**移動のときは -1。**
     * 
     * ⚠️ **駒台のどの駒を掴んだかを突き合わせるのはこの値。** 駒台の駒は
     * マスを持たないので、From では表せない。
     */
    "drop": number;

    /**
     * ToRank / ToFile は移動先（打ち先）。
     */
    "toRank": number;
    "toFile": number;

    /**
     * Promote は成るか。
     * 
     * ⚠️ **同じ移動先に成りと不成の 2 つが並ぶことがある。** どちらを指すかは
     * 人が決めることなので、**片方に丸めないこと**（UI が聞く）。
     */
    "promote": boolean;
}
